ClangBuiltLinux/continuous-integration2

generate_tuxbuild.py, mainline.tux.yml, next.tux.yml
This was a recent change in tuxbuild to support make vars.
https://gitlab.com/Linaro/tuxbuild#passing-make-variables-in-build-set
Fixes #12
=> use clang-nightly with LLVM=1 make var

.github/workflows/mainline.yml, .github/workflows/next.yml, generate_workflow.py
=> hash job name

.github/workflows/mainline.yml, .github/workflows/next.yml, job_fragment.yml
This will obviously require an update in the repo settings.
=> ci2: TUXBUILD_TOKEN -> TUXSUITE_TOKEN

.github/workflows/mainline.yml, .github/workflows/next.yml, generate_workflow.py, generator.yml, job_fragment.yml
=> Move cron schedules into generator.yml

.github/workflows/4.19.yml, .github/workflows/5.4.yml, .github/workflows/android-5.4.yml, generator.yml, tuxsuite/4.19.tux.yml, tuxsuite/5.4.tux.yml, tuxsuite/android-5.4.tux.yml
I've been working on this as part of Android S.
=> enable LLVM_IAS=1 for arm64/x86_64 back to 4.19

.github/workflows/4.14.yml, generator.yml
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/53
=> Re-enable boot on 4.14 for x86_64

.github/workflows/4.14.yml, .github/workflows/4.19.yml, .github/workflows/4.4.yml, .github/workflows/4.9.yml, .github/workflows/5.10.yml, .github/workflows/5.4.yml, .github/workflows/android-4.14.yml, .github/workflows/android-4.19.yml, .github/workflows/android-4.9.yml, .github/workflows/android-5.10.yml, .github/workflows/android-5.4.yml, .github/workflows/android-mainline.yml, .github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, utils.py
Part one of https://github.com/ClangBuiltLinux/continuous-integration2/issues/62. There is no functional change, this is just matching reality.
=> llvm_tot is now 13

.github/workflows/5.10.yml, .github/workflows/5.4.yml, .github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, tuxsuite/5.10.tux.yml, tuxsuite/5.4.tux.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml
See linked issue in comments for issues. Based on #79.
=> Disable pseries_defconfig on LLVM 13

.github/workflows/5.10.yml, .github/workflows/android-4.14.yml, .github/workflows/android-4.19.yml, .github/workflows/android-4.9.yml, .github/workflows/android-5.10.yml, .github/workflows/android-5.4.yml, .github/workflows/android-mainline.yml, .github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, tuxsuite/5.10.tux.yml, tuxsuite/android-4.14.tux.yml, tuxsuite/android-4.19.tux.yml, tuxsuite/android-4.9.tux.yml, tuxsuite/android-5.10.tux.yml, tuxsuite/android-5.4.tux.yml, tuxsuite/android-mainline.tux.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/62
=> Add support for LLVM 12

.github/workflows/5.10.yml, .github/workflows/next.yml, generator.yml, tuxsuite/5.10.tux.yml, tuxsuite/next.tux.yml
The issues have been resolved so let's get the coverage while we can :)
=> Enable more some more configs on 5.10 and next

.github/workflows/5.10.yml, .github/workflows/mainline.yml, .github/workflows/next.yml, .github/workflows/tip.yml, generator.yml, tuxsuite/5.10.tux.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml, tuxsuite/tip.tux.yml
I have tested this through TuxSuite locally.
=> Drop CONFIG_UBSAN_UNSIGNED_OVERFLOW from all*configs

.github/workflows/lto-cfi-tip.yml, .github/workflows/lto-cfi.yml, .github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, tuxsuite/lto-cfi-tip.tux.yml, tuxsuite/lto-cfi.tux.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml
A follow up to @kees's request in #94.
I testing this via tuxsuite a few days ago and everything looked good. Hopefully nothing has regressed since then :)
=> Test allmodconfig with LTO and defconfig with full LTO

.github/workflows/android-5.10.yml, .github/workflows/android-5.4.yml, .github/workflows/android-mainline.yml, generator.yml, tuxsuite/android-5.10.tux.yml, tuxsuite/android-5.4.tux.yml, tuxsuite/android-mainline.tux.yml
=> Add Android ARCH=arm LLVM_IAS=1 5.4+ coverage

.github/workflows/4.14.yml, .github/workflows/4.19.yml, .github/workflows/4.4.yml, .github/workflows/4.9.yml, .github/workflows/5.10.yml, .github/workflows/5.4.yml, .github/workflows/android-4.14.yml, .github/workflows/android-4.19.yml, .github/workflows/android-4.9.yml, .github/workflows/android-mainline.yml, .github/workflows/android12-5.10.yml, .github/workflows/android12-5.4.yml, .github/workflows/android13-5.10.yml, .github/workflows/arm64-fixes.yml, .github/workflows/arm64.yml, .github/workflows/lto-cfi-tip.yml, .github/workflows/lto-cfi.yml, .github/workflows/mainline.yml, .github/workflows/next.yml, .github/workflows/tip.yml, generate_workflow.py
The problem matcher needs to be in the individual boot jobs, not the
TuxSuite ones.
=> Fix problem matcher

.github/workflows/android12-5.10.yml, .github/workflows/android12-5.4.yml, .github/workflows/android13-5.10.yml, generator.yml, tuxsuite/android12-5.10.tux.yml, tuxsuite/android12-5.4.tux.yml, tuxsuite/android13-5.10.tux.yml
Will open for acceptance when this CL has been merged:
https://android-review.googlesource.com/c/kernel/common/+/1702384
=> Enable LLVM_IAS=1 for Android arm32 allmodconfig with LLVM 13

.github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml
We don't want to merge this until https://gitlab.com/Linaro/tuxsuite/-/issues/107 is resolved, otherwise builders will fail.
=> Hexagon CI coverage

.github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml
The issue has been fixed in tip of tree.
=> Enable boot for ppc32 on -next and mainline with LLVM 13

.github/workflows/next.yml, generator.yml, tuxsuite/next.tux.yml
The fixes are available now:
https://git.kernel.org/next/linux-next/c/e347004468fd
https://git.kernel.org/next/linux-next/c/ee2d522ee125
https://git.kernel.org/next/linux-next/c/84aa00a141b7
=> Re-enable Hexagon on -next

.github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml
Currently blocked on https://github.com/ClangBuiltLinux/linux/issues/1431
=> Add `ARCH=riscv allmodconfig`

generate_tuxsuite.py, generate_workflow.py, generator.yml, patches/mainline.mbox
This series should make mainline mostly green through some configuration changes and a patch series. This is marked as a draft for now because of https://gitlab.com/Linaro/tuxsuite/-/issues/132 but it can still be reviewed to make sure the theory is okay. Once this is approved, I will do the same thing for -next.
NOTE: It seems like Linus has [a better patch](https://lore.kernel.org/r/CAHk-=whiQBofgis_rkniz8GBP9wZtSZdcDEffgSLO62BUGV3gg@mail.gmail.com/) than my 3/3 in the series but I did not feel like pulling it down right now. It is possible he will just apply it directly.
=> Make mainline green

check_logs.py, utils.py
I wanted to learn the CI system, so I ran off and implemented a solution to the feature request I reported. ;)
=> Add .config artifact checker

.github/workflows/next.yml, generator.yml, tuxsuite/next.tux.yml
The commits should be self explanatory, let me know if there are any issues!
=> Disable some builds to make -next green

check_logs.py
There are times where there are issues with fetching items from
TuxSuite, usually as a result of Amazon Web Services timing out or
having an internal server error. These failures make it difficult to
tell when there is actually an issue worth looking into vs. "oh, just
another fetch failure".
To fix this, attempt to fetch the item at least seven times, backing off
by 2^(current retry number) seconds each time.
Certain errors, such as a 404 error, will result in an immediate
failure because there is nothing to fetch.
NOTE: I have not actually tested this but I think the logic is sound.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/213
=> check_logs.py: Try multiple times to fetch items with exponential backoff

.github/problem-matchers/dtc.json, .github/problem-matchers/generic.json, .github/problem-matchers/modpost.json, check_logs.py
The commit messages should sufficiently explain everything, let me know if there are any issues!
=> Add problem matchers for depmod, dtc, and modpost

.github/workflows/lint.yml
Resolves issues with installing `shfmt`.
=> Update shfmt workflow steps

README.md
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/234
=> README: Add 5.15 badge

.github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml
Prior to LLVM 13, there was a backend error: https://llvm.org/bz50838
=> Add Hexagon allmodconfig for mainline and next with LLVM 13+

check_logs.py
A couple of small improvements around `check_logs.py` that should help with triaging issues that arise.
=> Improve check_logs.py output

.github/workflows/5.15.yml, .github/workflows/mainline.yml, .github/workflows/next.yml, generator.yml, tuxsuite/5.15.tux.yml, tuxsuite/mainline.tux.yml, tuxsuite/next.tux.yml
Until this can get sorted out on the TuxSuite side.
Link: https://github.com/ClangBuiltLinux/continuous-integration2/issues/290
=> Disable CONFIG_DEBUG_INFO_BTF for Fedora configs

.github/workflows/mainline-clang-11.yml, .github/workflows/mainline-clang-12.yml, .github/workflows/mainline-clang-13.yml, .github/workflows/mainline-clang-14.yml, .github/workflows/mainline-clang-15.yml, .github/workflows/next-clang-11.yml, .github/workflows/next-clang-12.yml, .github/workflows/next-clang-13.yml, .github/workflows/next-clang-14.yml, .github/workflows/next-clang-15.yml, generator.yml, tuxsuite/mainline-clang-11.tux.yml, tuxsuite/mainline-clang-12.tux.yml, tuxsuite/mainline-clang-13.tux.yml, tuxsuite/mainline-clang-14.tux.yml, tuxsuite/mainline-clang-15.tux.yml, tuxsuite/next-clang-11.tux.yml, tuxsuite/next-clang-12.tux.yml, tuxsuite/next-clang-13.tux.yml, tuxsuite/next-clang-14.tux.yml, tuxsuite/next-clang-15.tux.yml
`tuxsuite` needs to support `ARCH=um`.
Link: https://gitlab.com/Linaro/tuxsuite/-/issues/157
=> Disable ARCH=um builds for now

.github/workflows/next-clang-11.yml, .github/workflows/next-clang-12.yml, .github/workflows/next-clang-android.yml, generator.yml, tuxsuite/next-clang-11.tux.yml, tuxsuite/next-clang-12.tux.yml, tuxsuite/next-clang-android.tux.yml
While we triage https://github.com/ClangBuiltLinux/linux/issues/1615.
=> Disable ARCH=arm allyesconfig on -next

.github/workflows/mainline-clang-11.yml, .github/workflows/mainline-clang-12.yml, generator.yml, tuxsuite/mainline-clang-11.tux.yml, tuxsuite/mainline-clang-12.tux.yml
Same as a9d8571b91a5b19cd6a48780ed2231938a25283f, but for mainline.
=> Disable ARCH=arm allyesconfig on mainline

.github/workflows/mainline-clang-11.yml, .github/workflows/mainline-clang-12.yml, .github/workflows/mainline-clang-13.yml, .github/workflows/mainline-clang-14.yml, .github/workflows/mainline-clang-15.yml, .github/workflows/next-clang-11.yml, .github/workflows/next-clang-12.yml, .github/workflows/next-clang-13.yml, .github/workflows/next-clang-14.yml, .github/workflows/next-clang-15.yml, generator.yml, tuxsuite/mainline-clang-11.tux.yml, tuxsuite/mainline-clang-12.tux.yml, tuxsuite/mainline-clang-13.tux.yml, tuxsuite/mainline-clang-14.tux.yml, tuxsuite/mainline-clang-15.tux.yml, tuxsuite/next-clang-11.tux.yml, tuxsuite/next-clang-12.tux.yml, tuxsuite/next-clang-13.tux.yml, tuxsuite/next-clang-14.tux.yml, tuxsuite/next-clang-15.tux.yml
This is now supported in TuxSuite.
Link: https://gitlab.com/Linaro/tuxsuite/-/issues/157
=> Turn on ARCH=um builds again

.github/workflows/5.15-clang-12.yml, .github/workflows/next-clang-android.yml, .github/workflows/stable-clang-12.yml, generator.yml, tuxsuite/next-clang-android.tux.yml
A small series to enable certain build and boot tests and remove some commented out builds that will never be re-enabled. See the individual commits for the details.
=> Clean up generator.yml (August 10th, 2022)

.github/workflows/5.15-clang-11.yml, .github/workflows/5.15-clang-12.yml, .github/workflows/mainline-clang-11.yml, .github/workflows/mainline-clang-12.yml, .github/workflows/next-clang-11.yml, .github/workflows/next-clang-12.yml, .github/workflows/stable-clang-11.yml, .github/workflows/stable-clang-12.yml, generator.yml, tuxsuite/5.15-clang-11.tux.yml, tuxsuite/5.15-clang-12.tux.yml, tuxsuite/mainline-clang-11.tux.yml, tuxsuite/mainline-clang-12.tux.yml, tuxsuite/next-clang-11.tux.yml, tuxsuite/next-clang-12.tux.yml, tuxsuite/stable-clang-11.tux.yml, tuxsuite/stable-clang-12.tux.yml
Link: https://github.com/ClangBuiltLinux/linux/issues/1719
=> Disable OpenSUSE's RISC-V configuration when using GNU as

.github/workflows/5.15-clang-12.yml, .github/workflows/5.15-clang-13.yml, .github/workflows/5.15-clang-14.yml, .github/workflows/5.15-clang-15.yml, .github/workflows/5.15-clang-16.yml, .github/workflows/mainline-clang-14.yml, .github/workflows/mainline-clang-15.yml, .github/workflows/mainline-clang-16.yml, .github/workflows/next-clang-14.yml, .github/workflows/next-clang-15.yml, .github/workflows/next-clang-16.yml, .github/workflows/stable-clang-14.yml, .github/workflows/stable-clang-15.yml, .github/workflows/stable-clang-16.yml, generator.yml, tuxsuite/5.15-clang-12.tux.yml, tuxsuite/5.15-clang-13.tux.yml, tuxsuite/5.15-clang-14.tux.yml, tuxsuite/5.15-clang-15.tux.yml, tuxsuite/5.15-clang-16.tux.yml, tuxsuite/mainline-clang-14.tux.yml, tuxsuite/mainline-clang-15.tux.yml, tuxsuite/mainline-clang-16.tux.yml, tuxsuite/next-clang-14.tux.yml, tuxsuite/next-clang-15.tux.yml, tuxsuite/next-clang-16.tux.yml, tuxsuite/stable-clang-14.tux.yml, tuxsuite/stable-clang-15.tux.yml, tuxsuite/stable-clang-16.tux.yml
See each commit message for the individual details/changes.
=> Adjust CFI builds for kCFI

.github/workflows/mainline-clang-14.yml, .github/workflows/mainline-clang-15.yml, .github/workflows/mainline-clang-16.yml, generator.yml, tuxsuite/mainline-clang-14.tux.yml, tuxsuite/mainline-clang-15.tux.yml, tuxsuite/mainline-clang-16.tux.yml
See each commit message for the individual details/changes.
=> Adjust CFI builds for kCFI in mainline

.github/workflows/tip-clang-11.yml, .github/workflows/tip-clang-12.yml, .github/workflows/tip-clang-13.yml, .github/workflows/tip-clang-14.yml, .github/workflows/tip-clang-15.yml, .github/workflows/tip-clang-16.yml, generator.yml, tuxsuite/tip-clang-11.tux.yml, tuxsuite/tip-clang-12.tux.yml, tuxsuite/tip-clang-13.tux.yml, tuxsuite/tip-clang-14.tux.yml, tuxsuite/tip-clang-15.tux.yml, tuxsuite/tip-clang-16.tux.yml
Due to increased memory pressure from objtool causing timeouts.
=> generator.yml: Disable x86_64 allyesconfig builds on -tip

.github/workflows/mainline-clang-17.yml, .github/workflows/next-clang-17.yml, .github/workflows/stable-clang-17.yml, generator.yml, tuxsuite/mainline-clang-17.tux.yml, tuxsuite/next-clang-17.tux.yml, tuxsuite/stable-clang-17.tux.yml
LLVM 17 has support for building these configurations in the same manner
as LLVM 18. Now that tuxmake supports it, enable it here.
Link: https://gitlab.com/Linaro/tuxmake/-/commit/0c5d02c99fe86445d16425ea080b1e197a37c194
=> Add LoongArch clang-17 builds

.github/workflows/mainline-clang-16.yml, .github/workflows/mainline-clang-17.yml, .github/workflows/mainline-clang-18.yml, .github/workflows/next-clang-16.yml, .github/workflows/next-clang-17.yml, .github/workflows/next-clang-18.yml, generator.yml, tuxsuite/mainline-clang-16.tux.yml, tuxsuite/mainline-clang-17.tux.yml, tuxsuite/mainline-clang-18.tux.yml, tuxsuite/next-clang-16.tux.yml, tuxsuite/next-clang-17.tux.yml, tuxsuite/next-clang-18.tux.yml
Apply for #524 
Change generator.yml  and for mainline branch only because virtconfig is available in v6.3-rc1
=> Apply virtconfig to defconfig arm64

.github/workflows/mainline-clang-18.yml, .github/workflows/next-clang-18.yml, generator.yml, tuxsuite/mainline-clang-18.tux.yml, tuxsuite/next-clang-18.tux.yml
Apply for branch: kernel mainline and next
config: [arm64 hardening.config](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/configs/hardening.config), [x86_64 hardening.config](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/configs/hardening.config)
=> Add hardening.config

README.md
Some basics about the system + a diagram.
We can make more or less detailed as we see fit.
=> Add Caching Info Section to README

scripts/badge-caching/failing.svg, scripts/badge-caching/passing.svg, scripts/badge-caching/refresh.sh
Here's a dump of the crontab I'm running for scraping/caching badges.
=> badge-caching: Add the SVG templates and the refresh script

generator/generate_tuxsuite.py, generator/generate_workflow.py, ruff.toml
See the commit messages for the individual details.
=> Update for ruff 0.2.0

utils.py
I failed to notice this with commit 95516566 ("generator: yml: Update Alpine Linux configuration links").
=> utils.py: Update get_cbl_name() for new Alpine configuration scheme

.github/workflows/5.15-clang-21.yml, .github/workflows/6.1-clang-21.yml, .github/workflows/6.12-clang-21.yml, .github/workflows/6.6-clang-21.yml, .github/workflows/mainline-clang-21.yml, .github/workflows/next-clang-21.yml, .github/workflows/stable-clang-21.yml, tuxsuite/5.15-clang-21.tux.yml, tuxsuite/6.1-clang-21.tux.yml, tuxsuite/6.12-clang-21.tux.yml, tuxsuite/6.6-clang-21.tux.yml, tuxsuite/mainline-clang-21.tux.yml, tuxsuite/next-clang-21.tux.yml, tuxsuite/stable-clang-21.tux.yml
I forgot to account for #865 before merging the LLVM 21 update.
=> ci: Regenerate clang-21 GitHub Actions workflow and TuxSuite files
