- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generate_workflow.py
previously could produce invalid names,
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/481731328
errored with:
Names must start with a letter or '_' and contain only alphanumeric
characters, '-', or '_'.
It contained a `.` and `+` in -2.44522654963152E+18.
Also was not deterministic, so regenerating regenerated new hashes.
Prefix with `_`.
> Use deterministic MD5 hash

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- job_fragment.yml
We might be able to get fancier with these, based on how frequently
certain trees or toolchains get updated. For now, run something
continuously.
It seems that a whole workflow can only have one schedule...
> schedule cron jobs to run daily at midnight

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
We can enable all of the PowerPC builds for clang-12 because the issue
exposed by tuxmake has been fixed:
https://github.com/llvm/llvm-project/commit/0a23fbd28c7509f2f980946091e6055bf27164d2
We can enable ppc64le for clang-11 because it has the right target.
We cannot boot any of them because we do not have the right images.
> ci2: Enable some PowerPC builds

- .github/workflows/mainline.yml
- generator.yml
- tuxsuite/mainline.tux.yml
This will need to be rebased after #26 is merged and `clang-nightly` is broken right now due to  https://github.com/ClangBuiltLinux/linux/issues/1261.
> ci2: Add s390

- .gitignore
- check_logs.py
- utils.py
boot-qemu.sh supports booting an image with the full path to the image,
we do not need to fake a kernel directory.
> check_logs.py: Clean up image and dtb location handling

- .github/workflows/5.10.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- check_logs.py
- generator.yml
I am currently testing presubmit here: https://github.com/nathanchance/continuous-integration2/actions/runs/516468260
If all looks good, I can merge after approval.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/42
> Boot S390 kernels

- .github/workflows/4.14.yml
- .github/workflows/4.19.yml
- .github/workflows/4.4.yml
- .github/workflows/4.9.yml
- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/android-4.14.yml
- .github/workflows/android-4.19.yml
- .github/workflows/android-4.9.yml
- .github/workflows/android-5.10.yml
- .github/workflows/android-5.4.yml
- .github/workflows/android-mainline.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- README.md
- generate_workflow.py
All of the commit messages should be pretty self explanatory.
> Some small cleanups

- .github/workflows/android-4.19.yml
- .github/workflows/android-4.9.yml
- .github/workflows/android-5.10.yml
- .github/workflows/android-5.4.yml
- .github/workflows/android-mainline.yml
- generator.yml
- tuxsuite/android-4.19.tux.yml
- tuxsuite/android-4.9.tux.yml
- tuxsuite/android-5.10.tux.yml
- tuxsuite/android-5.4.tux.yml
- tuxsuite/android-mainline.tux.yml
two commits, one enables x86 since https://gitlab.com/Linaro/tuxmake/-/issues/117 is marked fixed. The other re-enables LLVM_IAS=1.
> enable LLVM_IAS=1 android x86 builds

- .github/workflows/android-4.14.yml
- tuxsuite/android-4.14.tux.yml
This was missed by commit b907f6f ("regen").
> ci2: Regenerate android-4.14 TuxSuite and workflow file

- .github/workflows/4.14.yml
- .github/workflows/4.19.yml
- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- check_logs.py
- generate_tuxsuite.py
- generator.yml
- install_deps.py
- tuxsuite/4.14.tux.yml
- tuxsuite/4.19.tux.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/5.4.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
- utils.py
I will rebase this on #71 after it is merged but I wanted to get ahead of this for review.
TuxSuite has merged support for `kernel_image` so we can add that to `generator.yml` for architectures that need it.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/1
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/27
> Enable booting MIPS and PowerPC kernels

- .github/workflows/5.10.yml
- generator.yml
- tuxsuite/5.10.tux.yml
These should not have been enabled:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/1874137744
https://github.com/ClangBuiltLinux/continuous-integration2/runs/1874137673
> Disable certain PowerPC builds with LLVM 11

- check_logs.py
- install_deps.py
The issue that necessitated building our own version of QEMU has been resolved.
I will send patches for qemu-binaries and boot-utils shortly.
> Move back to Ubuntu's qemu-system-riscv64

- .github/workflows/5.10.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
arm32_v6 isn't booting with IAS:
https://github.com/ClangBuiltLinux/linux/issues/1313
arm32_v7 is blocked on one last build issue:
https://github.com/ClangBuiltLinux/linux/issues/1286
arm32_all{mod|yes}config is blocked on some patches that will probably
land in the 5.12 merge window:
https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=9061/1
https://www.armlinux.org.uk/developer/patches/viewpatch.php?id=9062/1
I need to go chase backports back to 4.19.
> enable LLVM_IAS=1 for more 32b arm targets

- .github/workflows/clang-version.yml
- check-clang.sh
This has been ported over from the first continuous integration setup.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/95
> github: Add check-clang.sh workflow

- generate_workflow.py
Fixes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/98
> generate_workflow.py: Drop usedForSecurity in hashlib call

- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/5.4.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
malta_kvm_guest_defconfig is being proposed for deletion:
https://lore.kernel.org/r/20210301152958.3480-1-tsbogend@alpha.franken.de/
Switch to malta_defconfig plus `CONFIG_BLK_DEV_INITRD=y` so that we can
continue to boot userspace via `-initrd`.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/96
> Change MIPS base config

- utils.py
malta_defconfig is now the base, not malta_kvm_guest_defconfig.
> utils.py: Fix get_cbl_name() for mipsel

- .github/workflows/5.10.yml
- .github/workflows/mainline.yml
- generator.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/mainline.tux.yml
The patch fixing the build has been backported to all supported trees.
> Enable i386 builds on older trees

- .github/workflows/android-5.10.yml
- .github/workflows/android-5.4.yml
- .github/workflows/android-mainline.yml
- generator.yml
- tuxsuite/android-5.10.tux.yml
- tuxsuite/android-5.4.tux.yml
- tuxsuite/android-mainline.tux.yml
see also:
https://github.com/ClangBuiltLinux/linux/issues/1337
we could spin this down, but I'd rather have some coverage and work towards enabling LLVM_IAS=1/llvm_full for them.
Also, regardless of
https://github.com/ClangBuiltLinux/continuous-integration2/pull/115#issuecomment-810559773
I think we'll hit:
https://github.com/ClangBuiltLinux/linux/issues/1271
I have personal obligations today that I need to run to, I suggest merging these for tonight's CI run, then I'll clean up the rest tomorrow.
> Arm android cleanup

- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/android-mainline.tux.yml
- tuxsuite/android12-5.10.tux.yml
- tuxsuite/android12-5.4.tux.yml
- tuxsuite/android13-5.10.tux.yml
- tuxsuite/next.tux.yml
This should make all of the CI green; the x86 failures on -next are not addressed by this because the problem has been fixed in the KVM tree, it should be fixed when linux-next is updated tonight.
The patches should make sense individually, let me know if there are any problems.
> Make it green as of 4-26-2021

- .github/workflows/android-mainline.yml
- generator.yml
- tuxsuite/android-mainline.tux.yml
Android has started merging the 5.13 merges into android-mainline, meaning that we have the crypto fix that we need.
> Enable LLVM_IAS=1 for arm32 allmodconfig on android-mainline

- .github/workflows/mainline.yml
- generator.yml
Same as commit 499feb7 ("generator.yml: Disable boot for ppc32 on
-next") but for mainline, now that the commit that broke booting has
been merged. This can be enabled again once we have a fix on the LLVM
side.
> Disable boot for ppc32 on mainline

- .github/problem-matchers/clang-errors-warnings.json
- .github/workflows/4.14.yml
- .github/workflows/4.19.yml
- .github/workflows/4.4.yml
- .github/workflows/4.9.yml
- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/android-4.14.yml
- .github/workflows/android-4.19.yml
- .github/workflows/android-4.9.yml
- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- .github/workflows/arm64-fixes.yml
- .github/workflows/arm64.yml
- .github/workflows/lto-cfi-tip.yml
- .github/workflows/lto-cfi.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- .github/workflows/tip.yml
- generate_workflow.py
The problem matcher allows us to get clear visuals of errors/warnings:
https://github.com/actions/toolkit/blob/e9c6ee99a59ec34586d4374b68efe5cabfcee9db/docs/problem-matchers.md
https://github.com/linuxppc/linux-ci/actions/runs/826137942
Do note, I have not actually tested this but this is how it is wired up elsewhere.
> Add problem matcher

- .github/workflows/lto-cfi-tip.yml
- .github/workflows/lto-cfi.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/lto-cfi-tip.tux.yml
- tuxsuite/lto-cfi.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
Setting to draft for now as -next is broken and I do not want to introduce more breakage: https://lore.kernel.org/r/CA+G9fYsRZswjeDZj1hiGDu5HZ+jYCVsOOL6MAzEb=LVfQ1_NpA@mail.gmail.com/
@samitolvanen: Once this is merged, you can remove the commit that adds the `.config` fragments unless you find them useful.
> Build arm64 with CFI on mainline and next

- utils.py
```
Traceback (most recent call last):
File "./check_logs.py", line 102, in <module>
build = get_build()
File
"/home/runner/work/continuous-integration2/continuous-integration2/utils.py",
line 74, in get_build
llvm_version = get_requested_llvm_version()
File
"/home/runner/work/continuous-integration2/continuous-integration2/utils.py",
line 64, in get_requested_llvm_version
ver = int(os.environ["LLVM_VERSION"])
ValueError: invalid literal for int() with base 10: 'android'
```
> utils.py: Fix crash with LLVM_VERSION=android

- .github/workflows/4.14.yml
- .github/workflows/4.19.yml
- .github/workflows/4.4.yml
- .github/workflows/4.9.yml
- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/android-4.14.yml
- .github/workflows/android-4.19.yml
- .github/workflows/android-4.9.yml
- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- .github/workflows/arm64-fixes.yml
- .github/workflows/arm64.yml
- .github/workflows/lto-cfi-tip.yml
- .github/workflows/lto-cfi.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- .github/workflows/tip.yml
- generate_workflow.py
As far as I can tell, it is possible for the output_artifacts to get
overridden, resulting in builds that cannot be found:
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/836619133
Normally, defconfigs finish first but it is possible for a cached
allmodconfig to beat LTO'd defconfigs. To avoid this race, cache the
builds.json under a slightly more descriptive name using the build set
name as a suffix.
> Update artifact upload name

- check_logs.py
- install_deps.py
`check_logs.py` fails currently due to `ARCH=hexagon` not being handled. At the same time, I noticed that we should not have even run into this because `BOOT=0` means we should not even bother installing dependencies, which is the second commit.
> Fixup the Hexagon jobs and optimize around BOOT=0

- .github/workflows/next.yml
- generator.yml
- tuxsuite/next.tux.yml
AOSP LLVM does not have the patches that enable us to build arm64 with
LLVM=1 + CONFIG_CPU_BIG_ENDIAN=y, which were merged in LLVM 13:
https://github.com/llvm/llvm-project/commit/eea34aae2e74e9b6fbdd5b95f479bc7f397bf387
https://github.com/llvm/llvm-project/commit/7605a9a009b5fa3bdac07e3131c8d82f6d08feb7
On the kernel side, we restricted CONFIG_CPU_BIG_ENDIAN=y to LLVM 13:
https://git.kernel.org/linus/e9c6deee00e9197e75cd6aa0d265d3d45bd7cc28
As a result, we try to select CONFIG_CPU_BIG_ENDIAN but Kconfig makes us
silently fall back to CONFIG_CPU_LITTLE_ENDIAN=y, resulting in the
userspace boot failure seen here:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/2655483207?check_suite_focus=true
Disable this build until AOSP LLVM does a new build based on LLVM 13
with the …
> generator.yml: Disable arm64 big endian build with AOSP LLVM

- .github/workflows/4.14.yml
- .github/workflows/4.19.yml
- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/4.14.tux.yml
- tuxsuite/4.19.tux.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/5.4.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
This should resolve the vast majority of consistent failures over the past week or so.
The CI is pretty red for LLVM 13 because of an upstream issue, which [I reverted](https://github.com/llvm/llvm-project/commit/e6b086bef2c0597ed14b2aefbb3f6d74b94fd49e) but Debian's apt.llvm.org binaries built between the original patch and my revert :/ that should go away soon so it is not being dealt with here.
I'll ping the Hexagon patches today, hopefully that will be the first thing to get reverted.
> Deal with most of the current fires

- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/5.4.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
This was disabled because of [a `-Werror` issue](https://github.com/ClangBuiltLinux/linux/issues/1292). We disable -Werror for all
PowerPC builds because of a macro collision so we can re-enable this
build as well.
This matches PowerPC's own CI:
https://git.kernel.org/powerpc/c/62e2871dfaf347501cf3fa6a999acd48679088c2
> Enable pseries_defconfig (ppc64) again

- .github/workflows/5.10.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
Thanks to @compnerd's fix:
https://reviews.llvm.org/rGbbea64250f65480d787e1c5ff45c4de3ec2dcda8
ClangBuiltLinux/linux#1023
ClangBuiltLinux/linux#1043
LLVM 13 (ToT) can now fully build RISCV defconfig again.
Split off the configs into riscv (defconfig) and riscv_no_efi. Older
versions of llvm should use riscv_no_efi.
Then keep the old riscv_llvm_full "tier," continue to use it for older
versions of llvm, but move llvm_tot back to use llvm_full.
> Re-support RISCV defconfig with LLVM=1 LLVM_IAS=1

- .github/workflows/next.yml
- generator.yml
- tuxsuite/next.tux.yml
This is no longer expected to work:
https://lore.kernel.org/r/YMtib5hKVyNknZt3@osiris/
> Disable s390 builds for clang 12 and earlier on -next

- .github/workflows/next.yml
- generator.yml
Towards the end of a release cycle, -next releases get later and later
since there are more merge conflicts and build errors to fight through,
meaning that with our current schedule, we often miss the version of
-next that is going to be released.
Push the time we start the builds by three hours, which should ensure
that -next is released by that time.
> Update the start time of the -next jobs

- check_logs.py
It is possible for there to be errors in the build that are not fatal:
https://builds.tuxbuild.com/1uccc7bvODo3jO9zwLBJBhrudAw/build.log
https://lore.kernel.org/r/20210625122902.4058783-1-stefanb@linux.vnet.ibm.com/
The result field in status.json will tell us if the build fatally
errored based on make's error status so use that instead so that we do
not have false positive failures.
> check_logs.py: Do not use number of errors to fail the build

- generator.yml
- tuxsuite/5.4.tux.yml
The compat vDSO for arm64 did not build upstream until 5.7 because of
the series associated with commit a5d442f50a41 ("arm64: vdso32: Enable
Clang Compilation"). That series was backported to Android 5.4 so we do
not need any changes there.
Link: https://github.com/ClangBuiltLinux/continuous-integration2/runs/2947999652?check_suite_focus=true
> Remove CROSS_COMPILE_COMPAT for upstream 5.4

- .github/workflows/5.10.yml
- generator.yml
- tuxsuite/5.10.tux.yml
5.10 has a different issue that was tangentially fixed in mainline,
requiring further investigation.
> Move RISC-V back to ld.bfd on 5.10

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
Individual commits should be self explanatory :)
> Update powerpc64le builds

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
- utils.py
Arch, Fedora, and OpenSUSE to start because their configurations are easily accessible from the web.
This is currently blocked on https://gitlab.com/Linaro/tuxsuite/-/issues/124 in its current form, I am just pushing for early review.
> Add some distribution configurations

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generate_tuxsuite.py
- generate_workflow.py
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
Right now, the distribution configurations are lumped in with the
all*configs set, which means that we cannot get boot results until all
of the all*configs are done building.
Separate out the distribution configs into their own set so that they
can be built then boot tested in parallel with the defconfigs and
allconfigs build sets.
> Add separate distribution configuration build set

- .github/workflows/4.14.yml
- .github/workflows/4.19.yml
- .github/workflows/4.4.yml
- .github/workflows/4.9.yml
- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/android-4.14.yml
- .github/workflows/android-4.9.yml
- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generate_workflow.py
- generator.yml
- tuxsuite/4.14.tux.yml
- tuxsuite/4.19.tux.yml
- tuxsuite/4.4.tux.yml
- tuxsuite/4.9.tux.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/5.4.tux.yml
- tuxsuite/android-4.14.tux.yml
- tuxsuite/android-4.9.tux.yml
- tuxsuite/android-mainline.tux.yml
- tuxsuite/android12-5.10.tux.yml
- tuxsuite/android12-5.4.tux.yml
- tuxsuite/android13-5.10.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
LLVM_IAS=1 is now the default in -next, meaning we need to specify
LLVM_IAS=0 to keep our builds green.
While some of these do not strictly need LLVM_IAS=0 because they are
used on older tree, it is better to be explicit than implicit.
> Explicitly specify LLVM_IAS=0

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- check_logs.py
- generator.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
> Enable sanitizer builds

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
It causes erratic panics that may be related to QEMU. In order to keep
the build green, disable this config.
> Disable CONFIG_ATOMIC64_SELFTEST for Fedora's i686 config

- .github/workflows/4.14.yml
- .github/workflows/4.19.yml
- .github/workflows/4.4.yml
- .github/workflows/4.9.yml
- .github/workflows/5.10.yml
- .github/workflows/5.4.yml
- .github/workflows/android-4.14.yml
- .github/workflows/android-4.19.yml
- .github/workflows/android-4.9.yml
- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- .github/workflows/arm64-fixes.yml
- .github/workflows/arm64.yml
- .github/workflows/lto-cfi-tip.yml
- .github/workflows/lto-cfi.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- .github/workflows/tip.yml
- generate_workflow.py
When the tuxsuite CLI errors out because of invalid input (such as an
invalid make variable), the "tuxsuite" step in GitHub Actions passes
but all the check_logs.py steps error because builds.json is not found.
This is a little cryptic because it seems like the kernel builds
happened but they really didn't.
To make it a little easier to triage failures like this, make the upload
artifacts step error out if builds.json is not found, which means the
tuxsuite client errored out before builds were started or there was
something fatal with the builds that did happen. No builds.json file
means that check_logs.py cannot run at all so there is no point in even
letting those jobs run.
> Error out if builds.json is not found

- check_logs.py
clang-11 and clang-12 builds with CONFIG_KASAN_SW_TAGS=y are incredibly
slow to boot up but clang-13 and newer builds are fine. Increase the
timeout if CONFIG_KASAN_SW_TAGS=y is in the list of configs so that we
are sure that the build timed out rather than being slow.
> check_logs.py: Increase timeout for CONFIG_KASAN_SW_TAGS builds

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
We enabled support for testing `CONFIG_KASAN` in #178 but I did not realize that s390 supported KASAN so let's add it for more coverage. This passes my local tests.
32-bit ARM also supports `CONFIG_KASAN` but unfortunately, there is [an outstanding bug](https://github.com/ClangBuiltLinux/linux/issues/1211), which is resolved with @nickdesaulniers 's [patch](https://lore.kernel.org/r/20210830213846.2609349-1-ndesaulniers@google.com/). Once that patch has been merged, we can do this same thing for `ARCH=arm`.
> Test CONFIG_KASAN on s390 with clang-13+

- .github/workflows/matrix-check.yml
- check-matrix.sh
GitHub Actions has a maximum of 256 jobs per matrix. In order to make
sure that we stay under this, add a workflow to check the number of jobs
in a TuxSuite matrix. The other workflows will never hit this number of
jobs so we just ignore them.
> Check matrices for number of jobs

- .github/workflows/5.10.yml
- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- .github/workflows/arm64-fixes.yml
- .github/workflows/arm64.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- .github/workflows/tip.yml
- generator.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/android-mainline.tux.yml
- tuxsuite/android12-5.10.tux.yml
- tuxsuite/android12-5.4.tux.yml
- tuxsuite/android13-5.10.tux.yml
- tuxsuite/arm64-fixes.tux.yml
- tuxsuite/arm64.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
- tuxsuite/tip.tux.yml
`CONFIG_WERROR` is enabled by default when `CONFIG_COMPILE_TEST` is enabled.
Disable it explicitly so we can catch actual build breakage.
I am of the opinion we should prioritize getting warning clean so that
we can re-enable this, as this does not affect our boot tests anymore
but will make it obvious when there are potential issues due to
warnings.
> Disable -Werror for now

- check_logs.py
A follow up to #185 as there was another build that timed out at 15m.
Closes: #193
> check_logs.py: Increase timeout for CONFIG_KASAN (part 2)

- .github/workflows/lto-cfi-tip.yml
- .github/workflows/lto-cfi.yml
- generator.yml
- tuxsuite/lto-cfi-tip.tux.yml
- tuxsuite/lto-cfi.tux.yml
CONFIG_CFI_CLANG for x86_64 requires clang-13, meaning these builds
serve no purpose.
> Disable CONFIG_CFI_CLANG=y x86_64 builds with clang-12

- install_deps.py
After https://github.com/ClangBuiltLinux/boot-utils/pull/49
we use stdbuf from coreutils.
> remove expect package from install deps

- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
After increasing the timeout to 20m, there are still boot timeouts for
clang-11 and clang-12. It is likely that we would need to increase the
timeout to 40+ minutes so instead, just disable the boot tests.
> Disable boot for CONFIG_KASAN_SW_TAGS=y on clang-11 and clang-12

- patches/android-mainline/20210830_ndesaulniers_arm_select_have_futex_cmpxchg.patch
- patches/android-mainline/series
We are testing THUMB2 on android-mainline so we need this patch to avoid
boot failures.
> patches: Add futex patch to android-mainline

- check_logs.py
- utils.py
In the CI logs, QEMU output shows up before the rest of check_log.py
output. This is likely due to IO buffering, so explicitly flush buffers
in the helper routines and before spawning QEMU.
Signed-off-by: Kees Cook <keescook@google.com>
> Flush output buffers proactively

- check_logs.py
The current code chokes when there is an equals sign in the
configuration value:
`CONFIG_CMDLINE="console=ttyAMA0"`
```
Traceback (most recent call last):
File "./check_logs.py", line 169, in <module>
check_built_config(build)
File "./check_logs.py", line 85, in check_built_config
name, state = line.split('=')
ValueError: too many values to unpack (expected 2)
```
We just want to split on the first equals sign so add a max split of 1.
> check_logs.py: Handle equals sign in configuration value

- check_logs.py
Otherwise we're referring to classes not in scope, as seen in:
https://github.com/ClangBuiltLinux/continuous-integration2/runs/3767136408?check_suite_focus=true
Link: #213
Link: #214
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
> fully qualify error classes from urllib

- parse-debian-clang.sh
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/235
> parse-debian-clang.sh: Remove newlines between information print outs

- .github/workflows/5.4.yml
- generator.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/5.15.tux.yml
- tuxsuite/5.4.tux.yml
- tuxsuite/android-mainline.tux.yml
- tuxsuite/android12-5.10.tux.yml
- tuxsuite/android12-5.4.tux.yml
- tuxsuite/android13-5.10.tux.yml
- tuxsuite/arm64-fixes.tux.yml
- tuxsuite/arm64.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
TuxMake added CROSS_COMPILE_COMPAT to all arm64 make invocations,
meaning that CONFIG_COMPAT_VDSO is now enabled for all arm64 builds by
default. We had previously been adding CROSS_COMPILE_COMPAT to builds we
knew worked. Now, we have to disable CONFIG_COMPAT_VDSO for ones that we
know do not work, which is just 5.4.
This ends up simplifying our matrix as we will automatically get the
compat vDSO for any future builds we enable.
Link: https://gitlab.com/Linaro/tuxmake/-/commit/91cd7f1a85f76b7b120268362664c501157bb90e
> Remove CROSS_COMPILE_COMPAT and add CONFIG_COMPAT_VDSO=n build

- check_logs.py
This pull requests makes two changes to try and help triage failures a little bit easier:
1. Attempt to fetch artifacts if there was a 404 error.
2. Fetch the build's `status.json` if the build's `result` value from `tuxsuite`'s `builds.json` is neither `pass` nor `fail` (maybe a race between the `tuxsuite` client/backend?) to try and get an updated result.
Each commit has further information/motivation. This has not seen any formal testing yet but there is no obvious errors that I can see.
> Make failures more obvious

- generator.yml
- tuxsuite/4.14.tux.yml
- tuxsuite/4.19.tux.yml
- tuxsuite/4.4.tux.yml
- tuxsuite/4.9.tux.yml
- tuxsuite/5.10.tux.yml
- tuxsuite/5.15.tux.yml
- tuxsuite/5.4.tux.yml
- tuxsuite/android-4.14.tux.yml
- tuxsuite/android-4.19.tux.yml
- tuxsuite/android-4.9.tux.yml
- tuxsuite/android-mainline.tux.yml
- tuxsuite/android12-5.10.tux.yml
- tuxsuite/android12-5.4.tux.yml
- tuxsuite/android13-5.10.tux.yml
- tuxsuite/arm64-fixes.tux.yml
- tuxsuite/arm64.tux.yml
- tuxsuite/lto-cfi-tip.tux.yml
- tuxsuite/lto-cfi.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
- tuxsuite/tip.tux.yml
This series updates the targets that we call for TuxSuite, which will save us a little bit of work (maybe more for modules). See the individual commits for each change to understand the rationale.
> Change TuxSuite targets

- check_logs.py
TuxSuite's build.log shows the output of patch when a patch fails to
apply; print that log so that we can easily triage patch failures.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/261
> check_logs.py: Print build log and exit when patch fails to apply

- patches/android12-5.10/6ad8bbc9d301145335c35f29ed7878b61b0ad81f.patch
- patches/android12-5.10/series
This is in 5.10.77 but that version has not been merged into
android12-5.10 yet (as it is a released branch), which is currently at
5.10.66.
Apply this patch in the meantime so that the kernel continues to boot.
> patches: android12-5.10: Add patch to fix Thumb2 kernel boot on newer QEMU

- patches/mainline/0001-pinctrl-thunderbay-comment-process-of-building-funct.patch
- patches/mainline/0002-pinctrl-thunderbay-rework-loops-looking-for-groups-n.patch
- patches/mainline/series
- patches/next/0001-pinctrl-thunderbay-comment-process-of-building-funct.patch
- patches/next/0002-pinctrl-thunderbay-rework-loops-looking-for-groups-n.patch
- patches/next/series
This is not a clang specific build failure but it does impact our
ARCH=arm64 allmodconfig builds.
Link: https://lore.kernel.org/r/Yd2jcfXqqKHK%2FNaG@archlinux-ax161/
Link: https://lore.kernel.org/r/20220111172919.6567-1-zajec5@gmail.com/
> patches: Add a series to fix ARCH=arm64 with mainline and next

- patches/mainline/5d9224fb076e9a2023e0b06d6a164d644612c0c0.patch
- patches/mainline/series
This resolves a -Wuninitialized warning, which breaks our hexagon
allmodconfig build because -Werror is enabled (to catch problems like
this).
https://builds.tuxbuild.com/23hS2caXpXboLsIdKN7hdaLThbt/build.log
This patch is in the 5.17 branch so it should make it to Linus soon.
> patches/mainline: Add a SCSI patch from -next

- patches/mainline/b4c18c18ebf7cf1e602af88c12ef9cb0d6e5ce51.patch
- patches/mainline/series
The build is failing with OpenSUSE's s390x configuration:
https://builds.tuxbuild.com/24908cVXrmMMnMdKNyRVMRCO1sP/build.log
This was not noticed during the merge window because this configuration
had not been updated to build this driver; this only happened after
5.17-rc1 was released.
> patches: mainline: Add a patch for drivers/regulator/max20086-regulator.c

- .github/workflows/next.yml
- generator.yml
- tuxsuite/next.tux.yml
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/141
> Enable arm64 big endian build on -next with AOSP LLVM

- .github/workflows/android-4.19.yml
- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- generator.yml
- tuxsuite/android-4.19.tux.yml
- tuxsuite/android-mainline.tux.yml
- tuxsuite/android12-5.10.tux.yml
- tuxsuite/android12-5.4.tux.yml
- tuxsuite/android13-5.10.tux.yml
There are issues with the pahole version that TuxMake ships, which is
causing infrastructure issues. Until a fix can be developed, disable
BTF generation so that pahole does not run.
> Disable CONFIG_DEBUG_INFO_BTF for gki_defconfig

- .github/workflows/5.15.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/5.15.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
Fedora's 32-bit ARM config does not have CONFIG_DEBUG_INFO_BTF enabled
so it does not need CONFIG_DEBUG_INFO_BTF=n.
I missed the PowerPC configuration by mistake.
> Fix CONFIG_DEBUG_INFO_BTF=n for Fedora configs

- .github/workflows/5.15.yml
- .github/workflows/android-4.19.yml
- .github/workflows/android-mainline.yml
- .github/workflows/android12-5.10.yml
- .github/workflows/android12-5.4.yml
- .github/workflows/android13-5.10.yml
- .github/workflows/android13-5.15.yml
- .github/workflows/mainline.yml
- .github/workflows/next.yml
- generator.yml
- tuxsuite/5.15.tux.yml
- tuxsuite/android-4.19.tux.yml
- tuxsuite/android-mainline.tux.yml
- tuxsuite/android12-5.10.tux.yml
- tuxsuite/android12-5.4.tux.yml
- tuxsuite/android13-5.10.tux.yml
- tuxsuite/android13-5.15.tux.yml
- tuxsuite/mainline.tux.yml
- tuxsuite/next.tux.yml
pahole 1.22 has been backported to the tuxmake images so there should be
no more build failures.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/290
> Enable CONFIG_DEBUG_INFO_BTF for Android and Fedora configs

- patches/next/20220223_seanjc_kvm_x86_fix_pointer_mistmatch_warning_when_patching_ret0_static_calls.patch
- patches/next/series
Our allmodconfig ThinLTO builds disables `KASAN`, which causes `KVM_WERROR`
to be enabled due to the `default y if !KASAN`.
> patches: next: Add a patch to fix build with KVM_WERROR

- README.md
- check_logs.py
- scripts/check-patches.sh
- scripts/generate.sh
This fixes a few places where `.sh` scripts are being referenced by the old location, namely `check_logs.py`, which is causing the CI to fail currently.
NOTE: I intend to merge this without explicit approval once the checks pass to attempt to prevent the CI from going completely red.
> Fix up check_logs.py and messages/documentation after scripts move

- .github/workflows/mainline-clang-15.yml
- .github/workflows/next-clang-15.yml
- generator.yml
- tuxsuite/mainline-clang-15.tux.yml
- tuxsuite/next-clang-15.tux.yml
On mainline, SUSE's configuration needs to build with `LLVM_IAS=0` because
of https://github.com/ClangBuiltLinux/linux/issues/1418.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/265
> Build most powerpc64le configs with LLVM=1 LLVM_IAS=1

- .github/workflows/mainline-clang-15.yml
- .github/workflows/next-clang-15.yml
- generator.yml
- tuxsuite/mainline-clang-15.tux.yml
- tuxsuite/next-clang-15.tux.yml
This reverts commit fdee477c335ceda214b262c0e757310b7697028d, reversing
changes made to 3aa7dcd63ce27cd48ad67d30bf305288b7f432ad.
An ld.lld change in main breaks booting CONFIG_RELOCATABLE kernels,
which includes Fedora and OpenSUSE's configurations.
Revert this change for now, until a solution or appropriate workaround
can be created.
Link: https://github.com/ClangBuiltLinux/linux/issues/1581
NOTE: I intend to merge without explicit approval so the CI stays green through the weekend. I'll revisit this on Tuesday.
> Revert "Merge pull request #321 from nathanchance/ppc64le-llvm-ias"

- check_logs.py
The oopses problem matcher is not getting removed for KUnit runs as it
should:
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/1964728851
According to GitHub's official documentation, there should be two colons
at the end of the remove-matcher command but they are not present in the
check_logs.py print out. Add them to hopefully fix the problem matcher
getting disabled.
Link: https://github.com/actions/toolkit/blob/main/docs/commands.md#problem-matchers
> check_logs.py: Use proper syntax for removing problem matcher

- .github/workflows/stable-clang-15.yml
- generator.yml
- tuxsuite/stable-clang-15.tux.yml
We are applying patches to make 4eec5c448d09646659806afdd42b080a7002620f work in mainline. Given that the patches are unlikely to be stable material when merged, just revert 4eec5c448d09646659806afdd42b080a7002620f for stable.
Link: https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/2028368723
> Revert 4eec5c448d09646659806afdd42b080a7002620f for stable

- .github/workflows/android-mainline-clang-android.yml
- .github/workflows/next-clang-android.yml
- generator.yml
- tuxsuite/android-mainline-clang-android.tux.yml
- tuxsuite/next-clang-android.tux.yml
We can re-enable the disabled ARM builds because the compiler has been upgraded.
With the upgrade, we now trigger the ld.lld .plt bug for CONFIG_X86_KERNEL_IBT, so the builds that enable that config need to be disabled until the next compiler upgrade.
> Update AOSP LLVM builds

- .github/workflows/5.15-clang-11.yml
- .github/workflows/mainline-clang-11.yml
- .github/workflows/next-clang-11.yml
- .github/workflows/stable-clang-11.yml
- generator.yml
- tuxsuite/5.15-clang-11.tux.yml
- tuxsuite/mainline-clang-11.tux.yml
- tuxsuite/next-clang-11.tux.yml
- tuxsuite/stable-clang-11.tux.yml
This configuration has been dropped, as support for 32-bit x86 was
dropped in Fedora 31.
We do not actually lose much coverage, as we had this configuration
disabled for most recent clang versions due to
https://github.com/ClangBuiltLinux/linux/issues/1442.
Link: https://src.fedoraproject.org/rpms/kernel/c/ec96983c95a52f6df6e20e276ff9c761139e32d8
Link: https://fedoraproject.org/wiki/Changes/Stop_Building_i686_Kernels
> Remove Fedora i686 configuration

- check_logs.py
Sigh, I am too used to abbreviation...
Fixes: 6f56528 ("check_logs.py: Set execute bit for UML images before running 'boot-uml.sh'")
NOTE: I intend to merge this once presubmit completes to avoid further breakage.
> check_logs.py: Fix name of variable in run_boot()

- .github/workflows/next-clang-12.yml
- .github/workflows/next-clang-13.yml
- generator.yml
- tuxsuite/next-clang-12.tux.yml
- tuxsuite/next-clang-13.tux.yml
Commit e6f3b3c9c109 ("cfi: Use __builtin_function_start") in -next bumps
the required Clang version for CFI to 14.0.0, meaning our configuration
checks will now fail for clang-12 and clang-13. Disable these builds, as
they are no different from the ThinLTO ones.
Link: https://git.kernel.org/kees/c/e6f3b3c9c109ed57230996cf4a4c1b8ae7e36a81
Link: https://github.com/ClangBuiltLinux/continuous-integration2/runs/6114009943?check_suite_focus=true
> Disable arm64 CFI builds on -next for clang-{12,13}

- .github/workflows/clang-version.yml
This has not been running properly since commit 1c6961d ("Move shell
scripts to scripts/").
> github: workflows: Fix clang-version

- .github/workflows/mainline-clang-14.yml
- .github/workflows/next-clang-14.yml
- generator.yml
- tuxsuite/mainline-clang-14.tux.yml
- tuxsuite/next-clang-14.tux.yml
Same as commit 4eec5c4 ("generator.yml: Build powerpc64le configs with
LLVM=1 with LLVM ToT") but for LLVM 14, as the patch that allows us to
build with the integrated assembler has been merged into release/14.x:
https://github.com/llvm/llvm-project/commit/33504b3bbe10d5d4caae13efcb99bd159c126070
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/358
> Build powerpc64le configs with LLVM=1 with LLVM 14

- .github/workflows/chromeos-5.10-clang-12.yml
- .github/workflows/chromeos-5.10-clang-13.yml
- .github/workflows/chromeos-5.10-clang-14.yml
- .github/workflows/chromeos-5.10-clang-15.yml
- .github/workflows/chromeos-5.15-clang-12.yml
- .github/workflows/chromeos-5.15-clang-13.yml
- .github/workflows/chromeos-5.15-clang-14.yml
- .github/workflows/chromeos-5.15-clang-15.yml
- generate_tuxsuite.py
- generate_workflow.py
- tuxsuite/chromeos-5.10-clang-12.tux.yml
- tuxsuite/chromeos-5.10-clang-13.tux.yml
- tuxsuite/chromeos-5.10-clang-14.tux.yml
- tuxsuite/chromeos-5.10-clang-15.tux.yml
- tuxsuite/chromeos-5.15-clang-12.tux.yml
- tuxsuite/chromeos-5.15-clang-13.tux.yml
- tuxsuite/chromeos-5.15-clang-14.tux.yml
- tuxsuite/chromeos-5.15-clang-15.tux.yml
Currently, `generate_tuxsuite.py` and `generate_workflow.py` assume we
always generate a set of defconfig builds. However, it checks this by
looking for "defconfig" in the config, which is not true for the
ChromeOS configs. As a result, we generate an empty list of defconfigs,
which tuxsuite does not like.
To fix this, consider ChromeOS configurations defconfigs, as those are
the default configurations for the ChromeOS trees; they just do not live
in the arch folder because they are split up for the different boards
that are supported by ChromeOS.
Link: https://github.com/ClangBuiltLinux/continuous-integration2/runs/6400686892?check_suite_focus=true
> Fix ChromeOS runs

- .github/workflows/mainline-clang-12.yml
- .github/workflows/mainline-clang-13.yml
- generator.yml
- tuxsuite/mainline-clang-12.tux.yml
- tuxsuite/mainline-clang-13.tux.yml
The patch mentioned in commit 0060c13 ("generator.yml: Disable arm64 CFI
builds on -next for clang-{12,13}") is now in mainline.
> Disable arm64 CFI builds on mainline for clang-{12,13}

- patches/5.15/0001-objtool-Fix-symbol-creation.patch
I didn't realize until after I had made the initial commit that the
patch did not apply cleanly to 5.15 and I never updated this copy to
match. Do so now.
> patches: 5.15: Fix objtool patch

- utils.py
After the switch to `tuxsuite plan`, `builds.json` cannot be parsed
properly in `get_build()`:
```
Traceback (most recent call last):
File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 267, in <module>
build = verify_build()
File "/__w/continuous-integration2/continuous-integration2/./check_logs.py", line 58, in verify_build
build = get_build()
File "/__w/continuous-integration2/continuous-integration2/utils.py", line 138, in get_build
if build["target_arch"] == arch and \
TypeError: string indices must be integers
```
This is because the format of `builds.json` has been changed to be a
dictionary with a `builds` key and `tests` key, as opposed to a list of
build dictionaries like before.
To resolve this, get the values of the `build` dictionary, which will …
> utils.py: Adjust for new builds.json output with 'tuxsuite plan'

- patches/mainline/a44252d5c3bbd76efa7b65819712f0e2b1de54c0.patch
- patches/mainline/b7bf23c0865faac61564425ddc96a4a79ebf19b0.patch
- patches/mainline/series
The patch to enable `-Wformat` was merged before these fixes were
available in mainline. Apply them until they are merged so that we do
not have to disable `-Werror` for x86_64.
> patches: mainline: Add a couple in-flight -Wformat fixes

- patches/tip/eab9100d9898cbd37882b04415b12156f8942f18.patch
- patches/tip/series
This patch is needed in the -tip tree as well.
> patches: Add mchp-spdiftx.c to -tip trees

- patches/arm64/eab9100d9898cbd37882b04415b12156f8942f18.patch
I forgot to update this patch as part of #415. The previous version was
a backport targeting 5.19, this version applies to current mainline.
> patches: arm64: Update mchp-spdiftx.c patch

- .github/workflows/5.15-clang-16.yml
- .github/workflows/mainline-clang-16.yml
- .github/workflows/next-clang-16.yml
- .github/workflows/stable-clang-16.yml
- generator.yml
- tuxsuite/5.15-clang-16.tux.yml
- tuxsuite/mainline-clang-16.tux.yml
- tuxsuite/next-clang-16.tux.yml
- tuxsuite/stable-clang-16.tux.yml
Due to the issue linked. Once the kernel side change is finalized, it
can be applied and these builds can be re-enabled.
> Disable CONFIG_KCSAN builds for tip of tree LLVM

- .github/workflows/next-clang-16.yml
- generator.yml
- tuxsuite/next-clang-16.tux.yml
The patch that we need for ToT LLVM is now available:
https://git.kernel.org/next/linux-next/c/fdc1eea7a8473ca30ef8d180e3f99a4955155c7f
> Enable x86_64 KCSAN build on -next

- utils.py
Otherwise, `check_logs.py` will fail.
> utils.py: Handle OpenSUSE riscv64 configuration in get_cbl_name()

- scripts/markdown-badges.py
Organize the build badges in a tree/compiler table to make it easier to examine quickly for common patterns. E.g. "Oh, looks like ToT Clang broke all the kernels", or "Oh, something is -next broke every Clang version", etc.
Signed-off-by: Kees Cook <keescook@chromium.org>
> scripts/markdown-badges.py: Generate sorted table for build status

- patches/mainline/20221031_nathan_bpf_mark_bpf_arch_init_dispatcher_early_as___init_or_module.patch
- patches/mainline/series
- patches/next/20221031_nathan_bpf_mark_bpf_arch_init_dispatcher_early_as___init_or_module.patch
- patches/next/series
This error is breaking builds in mainline and -next. Apply the patch
that was sent upstream to resolve this.
> patches: Apply patch for bpf recordmcount issue

- .github/workflows/5.15-clang-11.yml
- .github/workflows/5.15-clang-12.yml
- .github/workflows/mainline-clang-11.yml
- .github/workflows/mainline-clang-12.yml
- .github/workflows/next-clang-11.yml
- .github/workflows/next-clang-12.yml
- .github/workflows/stable-clang-11.yml
- .github/workflows/stable-clang-12.yml
- generator.yml
- tuxsuite/5.15-clang-11.tux.yml
- tuxsuite/5.15-clang-12.tux.yml
- tuxsuite/mainline-clang-11.tux.yml
- tuxsuite/mainline-clang-12.tux.yml
- tuxsuite/next-clang-11.tux.yml
- tuxsuite/next-clang-12.tux.yml
- tuxsuite/stable-clang-11.tux.yml
- tuxsuite/stable-clang-12.tux.yml
The build failures for which this configuration was disabled have been
resolved in all of these trees.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/445
> Re-enable OpenSUSE's RISC-V configuration

- .github/workflows/stable-clang-12.yml
- .github/workflows/stable-clang-13.yml
- .github/workflows/stable-clang-14.yml
- .github/workflows/stable-clang-15.yml
- .github/workflows/stable-clang-16.yml
- generator.yml
- tuxsuite/stable-clang-12.tux.yml
- tuxsuite/stable-clang-13.tux.yml
- tuxsuite/stable-clang-14.tux.yml
- tuxsuite/stable-clang-15.tux.yml
- tuxsuite/stable-clang-16.tux.yml
Same as commit 4ea2e8d ("generator.yml: Disable ppc44x_defconfig builds
on mainline and -next") but for stable. This should have been done as
part of the latest stable bump.
Link: https://github.com/ClangBuiltLinux/linux/issues/1679
> Disable ppc44x_defconfig builds on stable

- check_logs.py
- utils.py
This PR adds some more explicit checks for situations that we have hit in TuxSuite, such as an empty builds.json or unfinished builds, which will help making triaging failures quicker.
> Add more checks for potential TuxSuite problems

- .github/workflows/mainline-clang-15.yml
- .github/workflows/mainline-clang-16.yml
- .github/workflows/next-clang-15.yml
- .github/workflows/next-clang-16.yml
- .github/workflows/tip-clang-11.yml
- .github/workflows/tip-clang-12.yml
- .github/workflows/tip-clang-13.yml
- .github/workflows/tip-clang-14.yml
- generator.yml
- tuxsuite/mainline-clang-15.tux.yml
- tuxsuite/mainline-clang-16.tux.yml
- tuxsuite/next-clang-15.tux.yml
- tuxsuite/next-clang-16.tux.yml
- tuxsuite/tip-clang-11.tux.yml
- tuxsuite/tip-clang-12.tux.yml
- tuxsuite/tip-clang-13.tux.yml
- tuxsuite/tip-clang-14.tux.yml
This adjusts mainline and -next to disable x86_64 allyesconfig to match -tip, while turning on x86_64 allyesconfig for -tip, as I do not believe the issue is reproducible there.
> Adjust x86_64 allyesconfig builds

- patches/mainline/fix-99cb0d917ff.patch
- patches/mainline/series
Commit 99cb0d917ffa ("arch: fix broken BuildID for arm64 and riscv")
exposed a GNU ld bug that is present in the version that tuxsuite uses.
We still rely on GNU ld for at least powerpc and s390, so this issue
breaks those builds.
Add Ard's tentative fix for the issue so our builds go back to green,
allowing us to easily catch other regressions.
Link: https://lore.kernel.org/CAMj1kXHqQoqoys83nEp=Q6oT68+-GpCuMjfnYK9pMy-X_+jjKw@mail.gmail.com/
NOTE: Due to holidays, I plan to merge this without explicit approval once presubmit comes back green, especially since this is unlikely to be necessary for an extended period of time.
> patches: mainline: Add tentative fix for 99cb0d917ff

- generate.py
- scripts/parse-debian-clang.py
- utils.py
Recent versions of pylint complain:
W0719: Raising too general exception: Exception (broad-exception-raised)
This does not truly matter since we do not expect these exceptions to be
caught but it is a simple change to make the linter happy. Use the more
specific but still accurate RuntimeError exception, which is used for
generic problems at runtime.
> Replace Exception with more specific RuntimeError

- .github/workflows/5.10-clang-11.yml
- .github/workflows/5.10-clang-12.yml
- generator.yml
- tuxsuite/5.10-clang-11.tux.yml
- tuxsuite/5.10-clang-12.tux.yml
Commit 82d3edb50a11 ("s390/cpum_sf: add READ_ONCE() semantics to compare
and swap loops") was applied to 5.10, where it started causing build
breakage with LLVM 11 and 12:
```
arch/s390/kernel/perf_cpum_sf.c:1234:3: error: inline asm error: This value type register class is not natively supported!
"       cdsg    %[old],%[new],%[ptr]\n"
^
warning: Compiler has made implicit assumption that TypeSize is not scalable. This may or may not lead to broken code.
```
The construct that is used in the inline assembly was only supported in
LLVM starting with the 13.0.0 release, even though it has been supported
in GCC for a while. This was the catalyst for commit e2bc3e91d91e
("scripts/min-tool-version.sh: Raise minimum clang version to 13.0.0 for
s390").
The min-tool-version.sh infrastructure does …
> Disable s390 builds with LLVM < 13 on 5.10

- .github/workflows/5.15-clang-17.yml
- .github/workflows/stable-clang-17.yml
- generator.yml
- tuxsuite/5.15-clang-17.tux.yml
- tuxsuite/stable-clang-17.tux.yml
The change for tip of tree LLVM has been backported to both of these
trees now so it is safe to re-enable these.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/424
> Enable KCSAN on stable

- patches/mainline/b9930311641cf2ed905a84aabe27e8f3868aee4a.patch
- patches/mainline/series
There was apparently a snafu with sending this change along with the one
it fixes. Apply the change in the meantime.
Link: https://lore.kernel.org/Y%2FeULFO4jbivQ679@dev-arch.thelio-3990X/
> patches: mainline: Add fix for host1x -Wuninitialized warning

- check_logs.py
- generate.py
- ruff.toml
[`ruff`](https://github.com/charliermarsh/ruff) is a fast Python linter written in Rust. Add a `ruff.toml` file to turn on several classes of warnings that are useful and fix them up.
> Add ruff.toml and clean up warnings

- .github/workflows/next-clang-15.yml
- .github/workflows/next-clang-16.yml
- .github/workflows/next-clang-17.yml
- generator.yml
- tuxsuite/next-clang-15.tux.yml
- tuxsuite/next-clang-16.tux.yml
- tuxsuite/next-clang-17.tux.yml
In order to use ld.lld (and by extension, LLVM=1) with allmodconfig
(which is big endian), we need to build with the ELFv2 ABI, as ld.lld
does not have support for the ELFv1 ABI. This is now possible on -next,
so wire up this build to make sure it stays green.
This adds 15 more builds per week:
```
diff --git a/tmp/estimate-builds.txt b/tmp/.psub.GnbBewMeWv
index 24a4a39..ad40946 100644
--- a/tmp/estimate-builds.txt
+++ b/tmp/.psub.GnbBewMeWv
@@ -1,4 +1,4 @@
-Total builds per week: 8148
+Total builds per week: 8163
- tree: mainline
total: 2900
@@ -12,11 +12,11 @@ Total builds per week: 8148
- clang-11: 520
- tree: next
-    total: 2150
+    total: 2165
breakdown:
-    - clang-17: 320
-    - clang-16: 320
-    - clang-15: 300
+    - clang-17: 325
+    - clang-16: 325
+    - clang-15: 305
- …
```
> Add powerpc allmodconfig build on linux-next

- .github/workflows/mainline-clang-15.yml
- .github/workflows/mainline-clang-16.yml
- .github/workflows/mainline-clang-17.yml
- .github/workflows/next-clang-15.yml
- .github/workflows/next-clang-16.yml
- .github/workflows/next-clang-17.yml
- .github/workflows/tip-clang-15.yml
- .github/workflows/tip-clang-16.yml
- .github/workflows/tip-clang-17.yml
- generator.yml
- tuxsuite/mainline-clang-15.tux.yml
- tuxsuite/mainline-clang-16.tux.yml
- tuxsuite/mainline-clang-17.tux.yml
- tuxsuite/next-clang-15.tux.yml
- tuxsuite/next-clang-16.tux.yml
- tuxsuite/next-clang-17.tux.yml
- tuxsuite/tip-clang-15.tux.yml
- tuxsuite/tip-clang-16.tux.yml
- tuxsuite/tip-clang-17.tux.yml
These were disabled due to a build time regression, which has since been
resolved in all of these trees. This increases the number of builds
slightly:
```diff
diff --git a/tmp/estimate-builds.txt b/tmp/.psub.3vT4MBu4zi
index ad40946..38964c1 100644
--- a/tmp/estimate-builds.txt
+++ b/tmp/.psub.3vT4MBu4zi
@@ -1,22 +1,22 @@
-Total builds per week: 8163
+Total builds per week: 8218
- tree: mainline
-    total: 2900
+    total: 2925
breakdown:
-    - clang-17: 630
-    - clang-16: 630
-    - clang-15: 295
+    - clang-17: 640
+    - clang-16: 640
+    - clang-15: 300
- clang-14: 280
- clang-13: 280
- clang-12: 265
- clang-11: 520
- tree: next
-    total: 2165
+    total: 2180
breakdown:
-    - clang-17: 325
-    - clang-16: 325
-    - clang-15: 305
+    - clang-17: 330
+    - clang-16: 330
+ …
```
> Turn x86_64 allyesconfig builds back on

- generator.yml
https://lore.kernel.org/llvm/20230401170117.1580840-1-masahiroy@kernel.org/ reminded me that we probably don't need to set CROSS_COMPILE any more. Nathan confirmed that tuxsuite doesn't allow setting this, and that these triples aren't consumed or emitted by generate.py.
> drop triples

- .github/workflows/android-mainline-clang-android.yml
- generator.yml
- tuxsuite/android-mainline-clang-android.tux.yml
Link: https://github.com/ClangBuiltLinux/continuous-integration2/issues/556
> Disable RISC-V gki_defconfig with llvm_android for now

- .github/workflows/chromeos-5.10-clang-12.yml
- .github/workflows/chromeos-5.10-clang-13.yml
- .github/workflows/chromeos-5.10-clang-14.yml
- .github/workflows/chromeos-5.10-clang-15.yml
- .github/workflows/chromeos-5.10-clang-16.yml
- .github/workflows/chromeos-5.10-clang-17.yml
- .github/workflows/chromeos-5.15-clang-12.yml
- .github/workflows/chromeos-5.15-clang-13.yml
- .github/workflows/chromeos-5.15-clang-14.yml
- .github/workflows/chromeos-5.15-clang-15.yml
- .github/workflows/chromeos-5.15-clang-16.yml
- .github/workflows/chromeos-5.15-clang-17.yml
- generator.yml
- tuxsuite/chromeos-5.10-clang-12.tux.yml
- tuxsuite/chromeos-5.10-clang-13.tux.yml
- tuxsuite/chromeos-5.10-clang-14.tux.yml
- tuxsuite/chromeos-5.10-clang-15.tux.yml
- tuxsuite/chromeos-5.10-clang-16.tux.yml
- tuxsuite/chromeos-5.10-clang-17.tux.yml
- tuxsuite/chromeos-5.15-clang-12.tux.yml
- tuxsuite/chromeos-5.15-clang-13.tux.yml
- tuxsuite/chromeos-5.15-clang-14.tux.yml
- tuxsuite/chromeos-5.15-clang-15.tux.yml
- tuxsuite/chromeos-5.15-clang-16.tux.yml
- tuxsuite/chromeos-5.15-clang-17.tux.yml
Our CrOS configurations have been failing to boot for quite some time
with:
```
[    1.934702] Freeing unused kernel memory: 1664K
[    1.937104] Run /init as init process
[    1.938678] audit: type=1400 audit(1.844:2): ChromeOS LSM: memfd execution attempt, cmd=(null), pid=1
[    1.939082] Chromium OS LSM: memfd execution blocked
[    1.939726] Failed to execute /init (error -13)
[    1.940373] Run /sbin/init as init process
[    1.943098] audit: type=1400 audit(1.849:3): ChromeOS LSM: memfd execution attempt, cmd=(null), pid=1
[    1.943460] Chromium OS LSM: memfd execution blocked
[    1.944104] Starting init: /sbin/init exists but couldn't execute it (error -13)
[    1.944424] Run /etc/init as init process
[    1.945941] Run /bin/init as init process
[    1.946948] Run /bin/sh as init …
```
> Fix ChromeOS boot testing

- .github/workflows/mainline-clang-15.yml
- .github/workflows/mainline-clang-16.yml
- .github/workflows/mainline-clang-17.yml
- generator.yml
- tuxsuite/mainline-clang-15.tux.yml
- tuxsuite/mainline-clang-16.tux.yml
- tuxsuite/mainline-clang-17.tux.yml
Now that my series to allow big endian ELFv2 to be selected with ld.lld
has been merged into mainline, we can start testing powerpc64
allmodconfig like -next, mirroring commit e4abcea ("generator: Add
PowerPC allmodconfig build").
This adds 25 builds per week:
```
diff --git a/tmp/estimate-builds.txt b/tmp/.psub.JyBf7GilsO
index 017dbea..b21671c 100644
--- a/tmp/estimate-builds.txt
+++ b/tmp/.psub.JyBf7GilsO
@@ -1,11 +1,11 @@
-Total builds per week: 8232
+Total builds per week: 8257
- tree: mainline
-    total: 2925
+    total: 2950
breakdown:
-    - clang-17: 640
-    - clang-16: 640
-    - clang-15: 300
+    - clang-17: 650
+    - clang-16: 650
+    - clang-15: 305
- clang-14: 280
- clang-13: 280
- clang-12: 265
```
> Add PowerPC allmodconfig build for mainline with LLVM 15+

- check_logs.py
Fixes:
```
check_logs.py:28:54: RUF010 [*] Use conversion in f-string
check_logs.py:37:54: RUF010 [*] Use conversion in f-string
```
Via:
`$ ruff check . --fix`
> check_logs: fix RUF010 warnings about f-strings

- .github/workflows/android-mainline-clang-android.yml
- generator.yml
- tuxsuite/android-mainline-clang-android.tux.yml
```diff
--- before.txt	2023-05-23 10:31:59.266672171 -0700
+++ after.txt	2023-05-23 10:31:46.806634649 -0700
@@ -1,4 +1,4 @@
-Total builds per week: 8257
+Total builds per week: 8262
- tree: mainline
total: 2950
@@ -101,7 +101,7 @@
- clang-11: 20
- tree: android-mainline
-    total: 90
+    total: 95
breakdown:
- clang-17: 25
- clang-16: 25
@@ -109,7 +109,7 @@
- clang-14: 5
- clang-13: 5
- clang-12: 5
-    - clang-android: 20
+    - clang-android: 25
- tree: android14-5.15
total: 76
```
> re-enable riscv_gki builds with llvm_android

- check_logs.py
15103a6 ("check_logs: fix RUF010 warnings about f-strings") added a conversion to silence a Ruff warning (`RUF010`). That warning has been updated in 0.0.273 to note that `f"{foo!s}"` is equivalent to `f"{foo}"`. The conversion is only needed if there is a format spec (such as a length).
This is the result of:
```
$ ruff --fix .
```
> check_logs.py: Remove unnecessary conversion to fix updated RUF010

- .github/workflows/android-mainline-clang-12.yml
- .github/workflows/android-mainline-clang-13.yml
- .github/workflows/android-mainline-clang-14.yml
- .github/workflows/android-mainline-clang-15.yml
- .github/workflows/android-mainline-clang-16.yml
- .github/workflows/android-mainline-clang-17.yml
- .github/workflows/android-mainline-clang-android.yml
- generator.yml
- tuxsuite/android-mainline-clang-12.tux.yml
- tuxsuite/android-mainline-clang-13.tux.yml
- tuxsuite/android-mainline-clang-14.tux.yml
- tuxsuite/android-mainline-clang-15.tux.yml
- tuxsuite/android-mainline-clang-16.tux.yml
- tuxsuite/android-mainline-clang-17.tux.yml
- tuxsuite/android-mainline-clang-android.tux.yml
After the linked change, `gki.config` does not exist, so the build fails.
As the change notes, `arch/riscv` now uses just `gki_defconfig` like arm64
and x86_64.
Link: https://android.googlesource.com/kernel/common/+/e5e65575783ef212a568077cbb6f850e1f5d07c9
> Update RISC-V gki_defconfig build

- .github/workflows/mainline-clang-12.yml
- .github/workflows/mainline-clang-13.yml
- .github/workflows/mainline-clang-14.yml
- .github/workflows/mainline-clang-15.yml
- .github/workflows/mainline-clang-16.yml
- .github/workflows/mainline-clang-17.yml
- .github/workflows/next-clang-12.yml
- .github/workflows/next-clang-13.yml
- .github/workflows/next-clang-14.yml
- .github/workflows/next-clang-15.yml
- .github/workflows/next-clang-16.yml
- .github/workflows/next-clang-17.yml
- generator.yml
- tuxsuite/mainline-clang-12.tux.yml
- tuxsuite/mainline-clang-13.tux.yml
- tuxsuite/mainline-clang-14.tux.yml
- tuxsuite/mainline-clang-15.tux.yml
- tuxsuite/mainline-clang-16.tux.yml
- tuxsuite/mainline-clang-17.tux.yml
- tuxsuite/next-clang-12.tux.yml
- tuxsuite/next-clang-13.tux.yml
- tuxsuite/next-clang-14.tux.yml
- tuxsuite/next-clang-15.tux.yml
- tuxsuite/next-clang-16.tux.yml
- tuxsuite/next-clang-17.tux.yml
After commit [9d90161ca5c7](https://git.kernel.org/linus/9d90161ca5c7234e80e14e563d198f322ca0c1d0) ("powerpc/64: Force ELFv2 when building with LLVM linker"), ELFv2 is the default when linking with `ld.lld`, which allows us to switch to normal `LLVM=1` when building `ppc64_guest_defconfig` on mainline and -next. IAS requires https://github.com/llvm/llvm-project/commit/33504b3bbe10d5d4caae13efcb99bd159c126070 from LLVM 14.x, so `LLVM_IAS=0` is still necessary for those builds.
I have qualified this locally with `scripts/build-local.py`.
> Move powerpc64 to LLVM=1 on mainline/-next with LLVM 14.x+

- scripts/build-local.py
This pull request adds some quality of life improvements to `scripts/build-local.py`.
The first commit allows local toolchains to be used with `tuxmake` by having something like:
```yaml
toolchain: clang
make_variables:
LLVM: 1
```
or
```yaml
toolchain: gcc
make_variables:
CROSS_COMPILE: aarch64-linux-
```
then running `build-local.py` like
```
$ PATH=$TC_PREFIX_1/bin:$TC_PREFIX_2/bin:$PATH scripts/build-local.py ...
```
This is useful for using the versions of GCC and LLVM available on [kernel.org](https://kernel.org/pub/tools) with `tuxmake`. `podman` or `docker` is not required in this instance, so the error is made conditional on whether or not versioned toolchains (ones with a `-` in them) are actually requested.
The second patch allows interrupting `build-local.py` with Ctrl-C. The …
> build-local.py improvements

- .github/workflows/mainline-clang-18.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/stable-clang-18.yml
- generator.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/next-clang-18.tux.yml
- tuxsuite/stable-clang-18.tux.yml
- utils.py
This is only enabled for clang-nightly at the moment but clang-17 should have it as well, which can be done after https://gitlab.com/Linaro/tuxmake/-/merge_requests/338 is merged and available in `tuxsuite`.
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/599
> Add support for LoongArch

- .github/workflows/mainline-clang-17.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/next-clang-17.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/stable-clang-17.yml
- .github/workflows/stable-clang-18.yml
- generator.yml
- tuxsuite/mainline-clang-17.tux.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/next-clang-17.tux.yml
- tuxsuite/next-clang-18.tux.yml
- tuxsuite/stable-clang-17.tux.yml
- tuxsuite/stable-clang-18.tux.yml
I missed that CONFIG_FTRACE needs to be disabled because LoongArch uses
recordmcount, which is not supported when building with LTO.
> Fix LoongArch LTO builds

- patches/android-4.14/0002-x86-mm-Fix-RESERVE_BRK-for-older-binutils.patch
- patches/android-4.19/0002-x86-mm-Fix-RESERVE_BRK-for-older-binutils.patch
While there have been no errors reported from this in CI yet, it is a
known issue with these patches, so fix them just in case.
Link: https://lore.kernel.org/CA+G9fYtS81+Tze6Zs0f908xXZ7zeMMEdpq65=betjDnyAkLn_g@mail.gmail.com/
> patches: Fix android-4.14 and android-4.19 brk backports

- utils.py
While virtconfig is currently an aarch64-only target, it could in theory become a target for other architectures as well, so handle it like just regular defconfigs.
> utils.py: Handle virtconfig

- .github/workflows/4.14-clang-18.yml
- .github/workflows/4.19-clang-18.yml
- .github/workflows/5.10-clang-18.yml
- .github/workflows/5.15-clang-18.yml
- .github/workflows/5.4-clang-18.yml
- .github/workflows/6.1-clang-18.yml
- .github/workflows/android-4.14-clang-18.yml
- .github/workflows/android-4.19-clang-18.yml
- .github/workflows/android-mainline-clang-18.yml
- .github/workflows/android12-5.10-clang-18.yml
- .github/workflows/android12-5.4-clang-18.yml
- .github/workflows/android13-5.10-clang-18.yml
- .github/workflows/android13-5.15-clang-18.yml
- .github/workflows/android14-5.15-clang-18.yml
- .github/workflows/android14-6.1-clang-18.yml
- .github/workflows/android15-6.1-clang-18.yml
- .github/workflows/arm64-clang-18.yml
- .github/workflows/arm64-fixes-clang-18.yml
- .github/workflows/chromeos-5.10-clang-18.yml
- .github/workflows/chromeos-5.15-clang-18.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/stable-clang-18.yml
- .github/workflows/tip-clang-18.yml
- generator.yml
There is currently a crash and infinite loop in clang's code generation,
which causes builds to fail or indefinitely hang. Due to the long
Thanksgiving weekend in the US, it is unlikely this issue will be fixed
before next week. Delay the LLVM tip of tree builds until Tuesday,
November 28th, so that TuxSuite is not tied up with known broken builds.
> Delay LLVM tip of tree builds until November 28th

- .github/workflows/tip-clang-17.yml
The caching infrastructure gets out of the way when using
workflow_dispatch, so we need to change the cron string to something
that will run right away when merged. This will be reverted once the job
has started.
> Temporarily change cron string to test caching

- .github/workflows/4.14-clang-18.yml
- .github/workflows/4.19-clang-18.yml
- .github/workflows/5.10-clang-18.yml
- .github/workflows/5.15-clang-18.yml
- .github/workflows/5.4-clang-18.yml
- .github/workflows/6.1-clang-18.yml
- .github/workflows/android-4.14-clang-18.yml
- .github/workflows/android-4.19-clang-18.yml
- .github/workflows/android-mainline-clang-18.yml
- .github/workflows/android12-5.10-clang-18.yml
- .github/workflows/android12-5.4-clang-18.yml
- .github/workflows/android13-5.10-clang-18.yml
- .github/workflows/android13-5.15-clang-18.yml
- .github/workflows/android14-5.15-clang-18.yml
- .github/workflows/android14-6.1-clang-18.yml
- .github/workflows/android15-6.1-clang-18.yml
- .github/workflows/arm64-clang-18.yml
- .github/workflows/arm64-fixes-clang-18.yml
- .github/workflows/chromeos-5.10-clang-18.yml
- .github/workflows/chromeos-5.15-clang-18.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/stable-clang-18.yml
- .github/workflows/tip-clang-18.yml
- generator.yml
This reverts commit e0069ac3bbfa858665eeff144f87ee1896e1c38d (#661).
While this was not as temporary as I would have hoped, the issue that was the catalyst for this delay has been fixed by reverting the counted_by attribute. Revert the delay so builds go back to their normal cadence.
> Revert #661

- .github/workflows/chromeos-5.10-clang-12.yml
- .github/workflows/chromeos-5.10-clang-13.yml
- .github/workflows/chromeos-5.10-clang-14.yml
- .github/workflows/chromeos-5.10-clang-15.yml
- .github/workflows/chromeos-5.10-clang-16.yml
- .github/workflows/chromeos-5.10-clang-17.yml
- .github/workflows/chromeos-5.10-clang-18.yml
- .github/workflows/chromeos-5.15-clang-12.yml
- .github/workflows/chromeos-5.15-clang-13.yml
- .github/workflows/chromeos-5.15-clang-14.yml
- .github/workflows/chromeos-5.15-clang-15.yml
- .github/workflows/chromeos-5.15-clang-16.yml
- .github/workflows/chromeos-5.15-clang-17.yml
- .github/workflows/chromeos-5.15-clang-18.yml
- generator.yml
- tuxsuite/chromeos-5.10-clang-12.tux.yml
- tuxsuite/chromeos-5.10-clang-13.tux.yml
- tuxsuite/chromeos-5.10-clang-14.tux.yml
- tuxsuite/chromeos-5.10-clang-15.tux.yml
- tuxsuite/chromeos-5.10-clang-16.tux.yml
- tuxsuite/chromeos-5.10-clang-17.tux.yml
- tuxsuite/chromeos-5.10-clang-18.tux.yml
- tuxsuite/chromeos-5.15-clang-12.tux.yml
- tuxsuite/chromeos-5.15-clang-13.tux.yml
- tuxsuite/chromeos-5.15-clang-14.tux.yml
- tuxsuite/chromeos-5.15-clang-15.tux.yml
- tuxsuite/chromeos-5.15-clang-16.tux.yml
- tuxsuite/chromeos-5.15-clang-17.tux.yml
- tuxsuite/chromeos-5.15-clang-18.tux.yml
These were renamed in ChromeOS commit [a5aa380698531](https://chromium-review.googlesource.com/q/I9303f8d0913dec8b496d89cac22cb2e1336b6705) ("CHROMIUM: config: arm64: Rename chromiumos-arm64.flavour.config"), which causes our builds to fail because the fragment could not be found.
A similar change will be needed for x86_64 but [that change](https://chromium-review.googlesource.com/q/I39c3a4fa9984cf3e86f4290b1fdd3f42b18519bd) is still pending a merge.
> Fix ChromeOS arm64 fragment name

- .github/workflows/6.6-clang-17.yml
- .github/workflows/6.6-clang-18.yml
- .github/workflows/mainline-clang-17.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/next-clang-17.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/stable-clang-17.yml
- .github/workflows/stable-clang-18.yml
- generator.yml
- tuxsuite/6.6-clang-17.tux.yml
- tuxsuite/6.6-clang-18.tux.yml
- tuxsuite/mainline-clang-17.tux.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/next-clang-17.tux.yml
- tuxsuite/next-clang-18.tux.yml
- tuxsuite/stable-clang-17.tux.yml
- tuxsuite/stable-clang-18.tux.yml
`CONFIG_RELOCATABLE` has been fixed since 6.7 with two changes (the first one fixes the build and the second one fixes boot):
[aa0cbc1b506b](https://git.kernel.org/linus/aa0cbc1b506b090c3a775b547c693ada108cc0d7) ("LoongArch: Record pc instead of offset in la_abs relocation")
[eea673e9d5ea](https://git.kernel.org/linus/eea673e9d5ea994c60b550ffb684413d3759b3f4) ("LoongArch: Apply dynamic relocations for LLD")
Re-enable `CONFIG_RELOCATABLE` (removing `CONFIG_CRASH_DUMP=n` as well, as it was only disabled to allow `CONFIG_RELOCATABLE` to be disabled) for all trees. [eea673e9d5ea](https://git.kernel.org/linus/eea673e9d5ea994c60b550ffb684413d3759b3f4) has been [flagged by `AUTOSEL` for 6.6](https://lore.kernel.org/stable/20231211135147.380223-45-sashal@kernel.org/) but it has not been added to …
> Update LoongArch builds for latest developments

- .github/workflows/next-clang-14.yml
- .github/workflows/next-clang-15.yml
- .github/workflows/next-clang-16.yml
- .github/workflows/next-clang-17.yml
- .github/workflows/next-clang-19.yml
- 0010-configs.yml
- 0012-llvm-14.yml
- 0012-llvm-15.yml
- 0012-llvm-16.yml
- 0012-llvm-latest.yml
- 0012-llvm-tot.yml
- tuxsuite/next-clang-14.tux.yml
- tuxsuite/next-clang-15.tux.yml
- tuxsuite/next-clang-16.tux.yml
- tuxsuite/next-clang-17.tux.yml
- tuxsuite/next-clang-19.tux.yml
RISC-V selects `CONFIG_ARCH_SUPPORTS_LTO_CLANG{,_THIN}` after https://git.kernel.org/riscv/c/021d23428bdbae032294e8f4a29cb53cb50ae71c, which is now in linux-next. Wire up builds to make sure this does not regress. A problem with linker relaxation in LLVM 15 and 16 prevents testing allmodconfig + ThinLTO with those versions.
> Add support for RISC-V LTO on -next

- caching/check.py
- caching/update.py
- utils.py
Currently, the frontend caching infrastructure is unaware of the patches being applied. This is problematic if we have changed either added, removed, or changed any patches since the previously cached run because the caching would skip the build even when the build's expected outcome would be different than the cached build's result.
Hash the contents of the patches folder using the hashlib library and add that to the cache so that when the patches folder changes at all, the cache is skipped and the build proceeds.
NOTE: I have not formally tested this but it seems like it should be sufficient. Please review carefully.
> caching: Add hash of contents of patches folder

- scripts/badge-caching/refresh.sh
- scripts/badge-caching/unknown.svg
Add an additional "unknown" state for if/when parsing of a fetched SVG fails to find either "passing" nor "failing".
Parse the README.md for yml URLs.
Log SVG scraping and ignore failures.
> badge-caching: Use README.md as source of truth

- .github/workflows/next-clang-18.yml
- generator/yml/0009-llvm-latest.yml
- tuxsuite/next-clang-18.tux.yml
LLVM 18.1.0-rc4 has all the fixes in LLVM that are needed to enable `LLVM=1` for s390 on -next, which has all the kernel side fixes.
> Switch s390 builds on -next with LLVM 18 over to LLVM=1

- .github/workflows/android-4.19-clang-android.yml
- .github/workflows/android-mainline-clang-android.yml
- .github/workflows/android12-5.10-clang-android.yml
- .github/workflows/android12-5.4-clang-android.yml
- .github/workflows/android13-5.10-clang-android.yml
- .github/workflows/android13-5.15-clang-android.yml
- .github/workflows/android14-5.15-clang-android.yml
- .github/workflows/android14-6.1-clang-android.yml
- .github/workflows/android15-6.1-clang-android.yml
- .github/workflows/android15-6.6-clang-android.yml
- .github/workflows/next-clang-android.yml
- generator/generate_tuxsuite.py
- generator/generate_workflow.py
- tuxsuite/android-4.19-clang-android.tux.yml
- tuxsuite/android-mainline-clang-android.tux.yml
- tuxsuite/android12-5.10-clang-android.tux.yml
- tuxsuite/android12-5.4-clang-android.tux.yml
- tuxsuite/android13-5.10-clang-android.tux.yml
- tuxsuite/android13-5.15-clang-android.tux.yml
- tuxsuite/android14-5.15-clang-android.tux.yml
- tuxsuite/android14-6.1-clang-android.tux.yml
- tuxsuite/android15-6.1-clang-android.tux.yml
- tuxsuite/android15-6.6-clang-android.tux.yml
- tuxsuite/next-clang-android.tux.yml
This accidentally acquired the `korg-` prefix, which obviously makes no sense since Android is its own toolchain vendor. Add the exception for it so that the correct container is used for both the cache check and the builds themselves.
> Fix clang-android builds

- utils.py
This should have been done in 4aac745 ("generator: Fix clang-androidbuilds").
> utils: Fix get_requested_llvm_version() for 'clang-android'

- .github/workflows/mainline-clang-18.yml
- .github/workflows/mainline-clang-19.yml
- generator/generate.py
- generator/yml/0009-llvm-latest.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/mainline-clang-19.tux.yml
For the same reason as commit 47f006b ("generator: yml: Switch s390 builds on -next with LLVM 18 over to LLVM=1"), as the kernel side fixes are now in Linus's tree.
The first change in this PR is needed to fix running `generator/generate.py`, which is required to apply the changes from this pull request, hence why it was included.
> Switch s390 builds on mainline with LLVM 18+ over to LLVM=1

- caching/update.py
I noticed that when patches fail to apply we don't get the best error message from `caching/update.py`:
```
...
RuntimeError: Could not find a suitable git sha or compiler version in any build
...
```
I wrote about this in #732.
Anyways, now we'll get an error message like this:
```
| Error: Some patches failed to apply.
| ['35f20786c481d5ced9283ff42de5c69b65e5ed13.patch']
```
Then, we can even have issues or PRs created auto-magically https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue.
Following that, it would just take a human reviewer to say "Yep, this patch has already been applied which has caused this failure; time to merge this robot's PR! I love robots 🤖"
> add better error handling for patches that fail to apply

- .github/workflows/5.10-clang-11.yml
- .github/workflows/5.10-clang-12.yml
- .github/workflows/5.15-clang-11.yml
- .github/workflows/5.15-clang-12.yml
- .github/workflows/6.1-clang-11.yml
- .github/workflows/6.1-clang-12.yml
- .github/workflows/6.6-clang-11.yml
- .github/workflows/6.6-clang-12.yml
- .github/workflows/mainline-clang-12.yml
- .github/workflows/stable-clang-12.yml
- generator/yml/0009-llvm-11.yml
- generator/yml/0009-llvm-12.yml
- tuxsuite/5.10-clang-11.tux.yml
- tuxsuite/5.10-clang-12.tux.yml
- tuxsuite/5.15-clang-11.tux.yml
- tuxsuite/5.15-clang-12.tux.yml
- tuxsuite/6.1-clang-11.tux.yml
- tuxsuite/6.1-clang-12.tux.yml
- tuxsuite/6.6-clang-11.tux.yml
- tuxsuite/6.6-clang-12.tux.yml
- tuxsuite/mainline-clang-12.tux.yml
- tuxsuite/stable-clang-12.tux.yml
After the upgrade from binutils 2.35.2 in Debian bullseye to binutils 2.40 in Debian bookworm, there is a build error:
```
llvm-objcopy: error: Link field value 24 in section .rel.dyn is not a symbol table
```
This is resolved in binutils 2.41 with commit [6b958fe36b7](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=6b958fe36b765f70878e8d3d002864967c4bc3a4) ("Setting sh_link for SHT_REL/SHT_RELA"). Once Debian has binutils 2.41 or newer, these builds can be re-enabled.
> Disable MIPS builds that use GNU ld

- .github/workflows/mainline-clang-14.yml
- .github/workflows/mainline-clang-15.yml
- .github/workflows/mainline-clang-16.yml
- .github/workflows/mainline-clang-17.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/mainline-clang-19.yml
- generator/yml/0009-llvm-14.yml
- generator/yml/0009-llvm-15.yml
- generator/yml/0009-llvm-16.yml
- generator/yml/0009-llvm-17.yml
- generator/yml/0009-llvm-latest.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/mainline-clang-14.tux.yml
- tuxsuite/mainline-clang-15.tux.yml
- tuxsuite/mainline-clang-16.tux.yml
- tuxsuite/mainline-clang-17.tux.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/mainline-clang-19.tux.yml
For the same reason as commit 9a01a2c ("Add support for RISC-V LTO on -next") but for mainline now that support has been merged.
> Enable RISC-V LTO builds on mainline

- .github/workflows/mainline-clang-17.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/mainline-clang-19.yml
- .github/workflows/next-clang-17.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/next-clang-19.yml
- .github/workflows/stable-clang-17.yml
- .github/workflows/stable-clang-18.yml
- .github/workflows/stable-clang-19.yml
- generator/yml/0007-configs.yml
- generator/yml/0009-llvm-17.yml
- generator/yml/0009-llvm-latest.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/mainline-clang-17.tux.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/mainline-clang-19.tux.yml
- tuxsuite/next-clang-17.tux.yml
- tuxsuite/next-clang-18.tux.yml
- tuxsuite/next-clang-19.tux.yml
- tuxsuite/stable-clang-17.tux.yml
- tuxsuite/stable-clang-18.tux.yml
- tuxsuite/stable-clang-19.tux.yml
Fedora builds with LTO when building with clang upstream, which is an important difference from how we currently build their configuration. Having side by side builds of LTO and no LTO is valuable for quickly narrowing down issues caused or exposed by LTO. Add a Fedora + ThinLTO build to match the official configuration and catch any regressions with this configuration from LLVM.
This is enabled for stable (6.8) and newer with LLVM 17 and newer to avoid adding too many builds to the matrix, which matches the versions of LLVM and the kernel that are in Fedora 40 and newer. This adds 90 builds per week.
Closes: https://github.com/ClangBuiltLinux/linux/issues/2009
> Add and enable Fedora LTO build

- patches/mainline/series
- patches/mainline/workaround-cbl-2014.patch
- patches/next/series
- patches/next/workaround-cbl-2014.patch
This warning should likely be fixed with a change on the LLVM side. While that is worked on, hide this instances with a localized `UBSAN_SANITIZE := n` for the affected file.
> patches: Add workaround for https://github.com/ClangBuiltLinux/linux/issues/2014

- .github/workflows/android-mainline-clang-12.yml
- .github/workflows/android-mainline-clang-13.yml
- .github/workflows/android-mainline-clang-14.yml
- .github/workflows/android-mainline-clang-15.yml
- .github/workflows/android-mainline-clang-16.yml
- .github/workflows/android-mainline-clang-17.yml
- .github/workflows/android-mainline-clang-18.yml
- .github/workflows/android-mainline-clang-19.yml
- .github/workflows/android-mainline-clang-android.yml
- generator/yml/0007-configs.yml
- generator/yml/0009-llvm-11.yml
- generator/yml/0009-llvm-12.yml
- generator/yml/0009-llvm-13.yml
- generator/yml/0009-llvm-14.yml
- generator/yml/0009-llvm-15.yml
- generator/yml/0009-llvm-16.yml
- generator/yml/0009-llvm-17.yml
- generator/yml/0009-llvm-latest.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/android-mainline-clang-12.tux.yml
- tuxsuite/android-mainline-clang-13.tux.yml
- tuxsuite/android-mainline-clang-14.tux.yml
- tuxsuite/android-mainline-clang-15.tux.yml
- tuxsuite/android-mainline-clang-16.tux.yml
- tuxsuite/android-mainline-clang-17.tux.yml
- tuxsuite/android-mainline-clang-18.tux.yml
- tuxsuite/android-mainline-clang-19.tux.yml
- tuxsuite/android-mainline-clang-android.tux.yml
Support for RISC-V is being dropped in Android's common kernel:
https://android-review.googlesource.com/c/kernel/common/+/3061966
> Drop RISC-V GKI builds

- .github/workflows/next-clang-16.yml
- .github/workflows/next-clang-17.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/next-clang-19.yml
- generator/yml/0007-configs.yml
- generator/yml/0009-llvm-16.yml
- generator/yml/0009-llvm-17.yml
- generator/yml/0009-llvm-latest.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/next-clang-16.tux.yml
- tuxsuite/next-clang-17.tux.yml
- tuxsuite/next-clang-18.tux.yml
- tuxsuite/next-clang-19.tux.yml
`CONFIG_CFI_CLANG` is [now supported for `ARCH=arm` on -next](https://git.kernel.org/next/linux-next/c/1a4fec49efe5273eb2fcf575175a117745f76f97). kCFI was first added in LLVM 16, so add an `ARCH=arm defconfig` + `CONFIG_CFI_CLANG=y` build when using LLVM 16 or newer.
> Add a CONFIG_CFI_CLANG build for ARCH=arm on -next with LLVM >= 16

- .github/workflows/mainline-clang-14.yml
- .github/workflows/mainline-clang-17.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/mainline-clang-19.yml
- generator/yml/0009-llvm-14.yml
- generator/yml/0009-llvm-17.yml
- generator/yml/0009-llvm-latest.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/mainline-clang-14.tux.yml
- tuxsuite/mainline-clang-17.tux.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/mainline-clang-19.tux.yml
This was missed when porting commit 9a01a2c ("Add support for RISC-V LTO on -next") from -next to mainline in commit 788146d ("generator: yml: Enable RISC-V LTO builds on mainline").
> Enable RISC-V allmodconfig ThinLTO builds on mainline

- scripts/build-local.py
```
scripts/build-local.py:167:43: E0606: Possibly using variable 'distro' before assignment (possibly-used-before-assignment)
```
> scripts/build-local.py: Add else with assertion to clear up new pylint warning

- .github/workflows/6.6-clang-18.yml
- .github/workflows/6.6-clang-20.yml
- .github/workflows/mainline-clang-18.yml
- .github/workflows/mainline-clang-20.yml
- .github/workflows/next-clang-18.yml
- .github/workflows/next-clang-20.yml
- .github/workflows/stable-clang-18.yml
- .github/workflows/stable-clang-20.yml
- generator/yml/0007-configs.yml
- tuxsuite/6.6-clang-18.tux.yml
- tuxsuite/6.6-clang-20.tux.yml
- tuxsuite/mainline-clang-18.tux.yml
- tuxsuite/mainline-clang-20.tux.yml
- tuxsuite/next-clang-18.tux.yml
- tuxsuite/next-clang-20.tux.yml
- tuxsuite/stable-clang-18.tux.yml
- tuxsuite/stable-clang-20.tux.yml
A recent change in linux-next allows this driver to be built with `CONFIG_COMPILE_TEST=y`, which causes a couple instances of `-Wframe-larger-than` to show up with `ARCH=loongarch`. This appears to be an issue in LLVM, for which I filed an issue. As this code won't actually run on LoongArch machines, just disable it to avoid having to turn off `CONFIG_WERROR` altogether with this configuration.
Link: https://github.com/ClangBuiltLinux/linux/issues/2038
> Disable CONFIG_DRM_OMAP with LoongArch configurations

- .github/workflows/5.15-clang-11.yml
- .github/workflows/5.15-clang-12.yml
- .github/workflows/5.15-clang-13.yml
- .github/workflows/5.15-clang-14.yml
- .github/workflows/5.15-clang-15.yml
- .github/workflows/5.15-clang-16.yml
- .github/workflows/5.15-clang-17.yml
- .github/workflows/5.15-clang-18.yml
- .github/workflows/5.15-clang-19.yml
- .github/workflows/5.15-clang-20.yml
- generator/yml/0009-llvm-11.yml
- generator/yml/0009-llvm-12.yml
- generator/yml/0009-llvm-13.yml
- generator/yml/0009-llvm-14.yml
- generator/yml/0009-llvm-15.yml
- generator/yml/0009-llvm-16.yml
- generator/yml/0009-llvm-17.yml
- generator/yml/0009-llvm-18.yml
- generator/yml/0009-llvm-latest.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/5.15-clang-11.tux.yml
- tuxsuite/5.15-clang-12.tux.yml
- tuxsuite/5.15-clang-13.tux.yml
- tuxsuite/5.15-clang-14.tux.yml
- tuxsuite/5.15-clang-15.tux.yml
- tuxsuite/5.15-clang-16.tux.yml
- tuxsuite/5.15-clang-17.tux.yml
- tuxsuite/5.15-clang-18.tux.yml
- tuxsuite/5.15-clang-19.tux.yml
- tuxsuite/5.15-clang-20.tux.yml
OpenSUSE recently [increased `CONFIG_NR_CPUS` to `8192` for the powerpc64leconfiguration](https://github.com/openSUSE/kernel-source/commit/20a31e9f1f5630dec71c579f76e63a593ebe3258) to match other architectures. Unfortunately, this breaks the build on 5.15 with:
```
arch/powerpc/kvm/book3s_64_entry.S:231: Error: operand out of range (0x109ba is not between 0xffffffffffff8000 and 0x7fff)
arch/powerpc/kvm/book3s_64_entry.S:384: Error: operand out of range (0x10178 is not between 0xffffffffffff8000 and 0x7fff)
arch/powerpc/kvm/book3s_64_entry.S:389: Error: operand out of range (0x10180 is not between 0xffffffffffff8000 and 0x7ffc)
arch/powerpc/kvm/book3s_hv_rmhandlers.S:551: Error: operand out of range (0x10148 is not between 0xffffffffffff8000 and 0x7fff) …
```
> Drop OpenSUSE's PowerPC configuration from 5.15

- patches/tip/series
- patches/tip/v2_20240916_dan_carpenter_iio_bmi323_fix_copy_and_paste_bugs_in_suspend_resume.patch
-tip is now synced with 6.12-rc1, which includes the warning addressed by the patch added in #777. Apply it to -tip for the same reason.
> patches: tip: Add iio bmi323 patch from mainline folder

- .github/workflows/next-clang-20.yml
- generator/yml/0005-architectures.yml
- generator/yml/0007-configs.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/next-clang-20.tux.yml
- utils.py
This is now supported in [tuxmake 1.28.4](https://gitlab.com/Linaro/tuxmake/-/merge_requests/456) and [boot-utils](https://github.com/ClangBuiltLinux/boot-utils/pull/122).
Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/786
> Add initial support for testing sparc64

- .github/workflows/mainline-clang-20.yml
- generator/yml/0009-llvm-tot.yml
- tuxsuite/mainline-clang-20.tux.yml
The changes needed to build `ARCH=sparc` with `clang` have [landed in mainline](https://git.kernel.org/linus/fbb3c22f908accfd6fd34b1dbdd304fc2609c78a).
> Enable sparc64 build on mainline

- scripts/check-patches-apply.py
For refs with a slash in them, such as the arm64 refs `for-next/core` and `for-next/fixes`, the tarball will be formatted like:
```
for-next/core/Makefile
for-next/core/arch/...
```
which causes an incorrect layout with the current value of 1 and patches that would normally apply correctly fail to do so. The strip value for the above scenario needs to be 2 to allow the patches to apply correctly. Use the length of the list created by splitting on slashes as the strip value so that the layout is consistent for patch application.
> scripts/check-patches-apply.py: Fix strip value for refs with a slash

- patches/6.12/8b55f8818900c99dd4f55a59a103f5b29e41eb2c.patch
- patches/6.12/series
This should have been transferred to 6.12 properly during the 6.12 and 6.13 update/split but I missed it.
> patches: 6.12: Apply 8b55f8818900c99dd4f55a59a103f5b29e41eb2c

- .github/workflows/mainline-clang-13.yml
- .github/workflows/next-clang-13.yml
- generator/yml/0009-llvm-13.yml
- tuxsuite/mainline-clang-13.tux.yml
- tuxsuite/next-clang-13.tux.yml
After commit [9aa0ebde0014](https://git.kernel.org/bpf/bpf-next/c/9aa0ebde0014f01a8ca82adcbf43b92345da0d50) ("bpf, verifier: Improve precision of BPF_MUL"), there is an error in certain ARM configurations that enable `CONFIG_BPF_SYSCALL`:
```
ld.lld: error: undefined symbol: __mulodi4
>>> referenced by verifier.c:14221 (/builds/linux/kernel/bpf/verifier.c:14221)
>>>               kernel/bpf/verifier.o:(adjust_reg_min_max_vals) in archive vmlinux.a
>>> referenced by verifier.c:14222 (/builds/linux/kernel/bpf/verifier.c:14222)
>>>               kernel/bpf/verifier.o:(adjust_reg_min_max_vals) in archive vmlinux.a
>>> referenced by verifier.c:14223 (/builds/linux/kernel/bpf/verifier.c:14223)
>>>               kernel/bpf/verifier.o:(adjust_reg_min_max_vals) in archive vmlinux.a
>>> referenced …
```
> Disable ARM configs with BPF enabled in -next with clang-13

- .github/workflows/mainline-clang-14.yml
- generator/yml/0009-llvm-14.yml
- tuxsuite/mainline-clang-14.tux.yml
Same as commit b8e27bf0 ("generator: yml: Disable RISC-V full LTO build on -next with LLVM 14") but for mainline now that the breaking asm goto with outputs changes have been merged there.
> Disable RISC-V full LTO build on mainline with LLVM 14

- utils.py
The previous fix in commit b04e3869 ("utils.py: Update get_cbl_name() for new Alpine configuration scheme") traded one error for another because I did not account for the period in the domain name. Index from the right to resolve the error more consistently. This has actually been tested locally now :^)
> utils.py: Fix get_cbl_name() for Alpine config change for real

- .github/problem-matchers/internal.json
The internal warnings/errors problem matcher regex still does not highlight the messages properly, even though I tested the regex. Unfortunately, the reason is only obvious when looking at the raw GitHublogs, which shows the raw color ASCII escape codes that `print_red()` and `print_yellow()` use.
Add the escape codes to the regex to fix the matching, which ends up making the matcher more robust because it will only highlight the color messages that the script generates.
> github: Fix internal problem matcher for color ASCII escape codes

- .github/workflows/5.15-clang-11.yml
- .github/workflows/5.15-clang-12.yml
- generator/yml/0009-llvm-11.yml
- generator/yml/0009-llvm-12.yml
- tuxsuite/5.15-clang-11.tux.yml
- tuxsuite/5.15-clang-12.tux.yml
Recently, ARCH=arm allyesconfig has started failing in the same way that necessitated disabling it on 6.1 and 6.6 with clang-11 and clang-12. Disable these builds, as this is not a high value target.
> Disable ARM allyesconfig on 5.15 with clang-11 and clang-12
